group1 = """{
    "words": [
        {"word": "john-kelly", "categories": ["Person", "Military"]},
        {"word": "nbc-nightly-news", "categories": ["Media", "TV Show", "News"]},
        {"word": "brent-bozell", "categories": ["Person", "Conservative"]},
        {"word": "looters", "categories": ["Social Issues", "Crime"]},
        {"word": "martin-o-malley", "categories": ["Politician", "Democrat"]},
        {"word": "oprah-winfrey", "categories": ["Person", "Entertainment"]},
        {"word": "marco-rubio", "categories": ["Politician", "Republican"]},
        {"word": "jim-acosta", "categories": ["Journalist", "Media", "CNN"]},
        {"word": "mexico", "categories": ["Country"]},
        {"word": "t-mobile", "categories": ["Company", "Technology"]},
        {"word": "us-mexico-trade-surplus", "categories": ["Economy", "Trade"]},
        {"word": "andrew-weissmann", "categories": ["Person", "Legal"]},
        {"word": "saudi-arabia", "categories": ["Country"]},
        {"word": "jackson-lee", "categories": ["Politician", "Democrat"]},
        {"word": "h1n1-response", "categories": ["Health", "Pandemic"]},
        {"word": "rand-paul", "categories": ["Politician", "Republican"]},
        {"word": "steve-rattner", "categories": ["Person", "Finance"]},
        {"word": "fox-news-polls", "categories": ["Media", "Polls"]},
        {"word": "tim-o-brien", "categories": ["Person", "Author"]},
        {"word": "chris-christie", "categories": ["Politician", "Republican"]},
        {"word": "katy-tur", "categories": ["Journalist", "Media"]},
        {"word": "karl-rove", "categories": ["Person", "Political Strategist"]},
        {"word": "rod-rosenstein", "categories": ["Person", "Legal"]},
        {"word": "los-angeles", "categories": ["City"]},
        {"word": "european-leaders", "categories": ["International Relations", "Leadership"]},
        {"word": "george-w-bush", "categories": ["Person", "Politician"]},
        {"word": "social-media", "categories": ["Technology", "Social Issues"]},
        {"word": "major-league-baseball", "categories": ["Sports", "Baseball"]},
        {"word": "tom-friedman", "categories": ["Person", "Journalist"]},
        {"word": "woodward-book", "categories": ["Book", "Author"]},
        {"word": "miles-taylor", "categories": ["Person"]},
        {"word": "democrats", "categories": ["Political Party"]},
        {"word": "nbc-polls", "categories": ["Media", "Polls"]},
        {"word": "ms-13", "categories": ["Criminal Organization"]},
        {"word": "samantha-bee", "categories": ["Entertainment", "Comedian"]},
        {"word": "the-haters", "categories": ["Social Issues"]},
        {"word": "john-huber", "categories": ["Person", "Legal"]},
        {"word": "danny-o-connor", "categories": ["Politician", "Democrat"]},
        {"word": "cynthia-nixon", "categories": ["Person", "Actor"]},
        {"word": "colin-powell", "categories": ["Person", "Politician"]},
        {"word": "who", "categories": ["Organization", "Health"]},
        {"word": "turkey", "categories": ["Country"]},
        {"word": "philip-mudd", "categories": ["Person"]},
        {"word": "???", "categories": ["Uncategorized"]},
        {"word": "tony-podesta", "categories": ["Person", "Lobbyist"]},
        {"word": "daily-beast", "categories": ["Media", "News Outlet"]},
        {"word": "al-schmidt", "categories": ["Person"]},
        {"word": "dan-mccready", "categories": ["Politician", "Democrat"]},
        {"word": "puerto-ricans", "categories": ["Ethnicity", "People"]},
        {"word": "washington-post", "categories": ["Media", "News Outlet"]},
        {"word": "doug-ducey", "categories": ["Politician", "Republican"]},
        {"word": "washington-dc", "categories": ["City"]},
        {"word": "obamacare", "categories": ["Healthcare", "Policy"]},
        {"word": "adam-schiff", "categories": ["Politician", "Democrat"]},
        {"word": "cooper-governor", "categories": ["Politician", "Democrat"]},
        {"word": "penn-jillette", "categories": ["Person", "Magician"]},
        {"word": "brian-williams", "categories": ["Journalist", "Media"]},
        {"word": "cnn", "categories": ["Media", "News Outlet"]},
        {"word": "bob-corker", "categories": ["Politician", "Republican"]},
        {"word": "charles-lane", "categories": ["Person", "Journalist"]},
        {"word": "chain-migration", "categories": ["Immigration", "Policy"]},
        {"word": "molly-sims", "categories": ["Person", "Model"]},
        {"word": "carter-page-fisa", "categories": ["Legal", "Surveillance"]},
        {"word": "bowe-bergdahl-decision", "categories": ["Legal", "Military"]},
        {"word": "cnn-trump-documentary", "categories": ["Media", "Documentary"]},
        {"word": "establishment", "categories": ["Social Issues", "Political"]},
        {"word": "nasa", "categories": ["Organization", "Science"]},
        {"word": "isis", "categories": ["Terrorist Organization"]},
        {"word": "rick-perry", "categories": ["Person", "Politician"]},
        {"word": "andrew-gillum", "categories": ["Politician", "Democrat"]},
        {"word": "marie-yovanovitch", "categories": ["Person", "Diplomat"]},
        {"word": "megyn-kelly", "categories": ["Person", "Journalist"]},
        {"word": "seal-prosecutors", "categories": ["Legal", "Military"]},
        {"word": "united-nations", "categories": ["Organization", "International Relations"]},
        {"word": "existing-border-wall", "categories": ["Politics", "Border Security"]},
        {"word": "dnc-emails", "categories": ["Politics", "Emails"]},
        {"word": "charles-krauthammer", "categories": ["Person", "Commentator"]},
        {"word": "chris-stirewalt", "categories": ["Person", "Political Analyst"]},
        {"word": "middle-east-relations", "categories": ["International Relations", "Politics"]},
        {"word": "gillian-turner", "categories": ["Person", "Journalist"]},
        {"word": "donny-deutsch", "categories": ["Person", "Media"]},
        {"word": "new-york-daily-news", "categories": ["Media", "News Outlet"]},
        {"word": "democratic-primaries", "categories": ["Politics", "Elections"]},
        {"word": "wall-street-journal-editorial-board", "categories": ["Media", "News Outlet"]},
        {"word": "democrat-run-cities", "categories": ["Politics", "Cities"]},
        {"word": "bob-iger", "categories": ["Person", "Business"]},
        {"word": "barbara-res", "categories": ["Person", "Business"]},
        {"word": "tony-schwartz", "categories": ["Person", "Author"]},
        {"word": "jeb-bush-supporters", "categories": ["Politician", "Republican"]},
        {"word": "fox-polls", "categories": ["Media", "Polls"]},
        {"word": "jonathan-martin", "categories": ["Person", "Journalist"]},
        {"word": "jeff-bezos", "categories": ["Person", "Business"]},
        {"word": "refugee-crisis-in-europe", "categories": ["International Relations", "Crisis"]},
        {"word": "blm", "categories": ["Movement", "Social Issues"]},
        {"word": "us-census", "categories": ["Government", "Data"]},
        {"word": "hillary-clinton", "categories": ["Person", "Politician"]},
        {"word": "robert-mueller", "categories": ["Person", "Legal"]},
        {"word": "david-green", "categories": ["Person", "Business"]},
        {"word": "our-visa-system", "categories": ["Government", "Immigration"]},
        {"word": "msnbc", "categories": ["Media", "News Outlet"]}
    ]
}"""
group2 = """{
  "words": [
    {"word": "stephen-sisolak", "categories": ["Politician", "Governor"]},
    {"word": "investigations-of-trump-presidency", "categories": ["Politics", "Investigations"]},
    {"word": "eric-schneiderman", "categories": ["Person", "Legal"]},
    {"word": "republican-party", "categories": ["Political Party"]},
    {"word": "lester-holt", "categories": ["Journalist", "Media"]},
    {"word": "hollywood", "categories": ["Entertainment"]},
    {"word": "ricardo-rossello", "categories": ["Politician", "Governor"]},
    {"word": "bret-stephens", "categories": ["Person", "Journalist"]},
    {"word": "bill-deblasio", "categories": ["Politician", "Mayor"]},
    {"word": "terrorists", "categories": ["Security", "Terrorism"]},
    {"word": "google", "categories": ["Company", "Technology"]},
    {"word": "stanley-mcchrystal", "categories": ["Person", "Military"]},
    {"word": "amy-mcgrath", "categories": ["Politician"]},
    {"word": "60-minutes", "categories": ["Media", "TV Show"]},
    {"word": "dick-durbin", "categories": ["Politician", "Democrat"]},
    {"word": "debra-messing", "categories": ["Person", "Actor"]},
    {"word": "pa-recount", "categories": ["Politics", "Elections"]},
    {"word": "the-media", "categories": ["Media"]},
    {"word": "tim-ryan", "categories": ["Politician", "Democrat"]},
    {"word": "alicia-machado", "categories": ["Person"]},
    {"word": "don-mcgahn", "categories": ["Person", "Legal"]},
    {"word": "minneapolis", "categories": ["City"]},
    {"word": "supreme-court", "categories": ["Legal"]},
    {"word": "truth-lies-leadership", "categories": ["Book", "Author"]},
    {"word": "collin-peterson", "categories": ["Politician", "Democrat"]},
    {"word": "graydon-carter", "categories": ["Person", "Journalist"]},
    {"word": "a-b-stoddard", "categories": ["Person", "Journalist"]},
    {"word": "virtual-learning", "categories": ["Education", "Technology"]},
    {"word": "wsj-editorial-board", "categories": ["Media", "Editorial Board"]},
    {"word": "lois-frankel", "categories": ["Politician", "Democrat"]},
    {"word": "uk-health-system", "categories": ["Healthcare", "International"]},
    {"word": "jonathan-karl", "categories": ["Journalist", "Media"]},
    {"word": "trade-pacts", "categories": ["Trade", "Politics"]},
    {"word": "merck-pharma", "categories": ["Company", "Pharmaceuticals"]},
    {"word": "steve-bullock", "categories": ["Politician", "Democrat"]},
    {"word": "ted-cruz", "categories": ["Politician", "Republican"]},
    {"word": "european-union", "categories": ["International Relations"]},
    {"word": "new-jersey", "categories": ["State"]},
    {"word": "jake-tapper", "categories": ["Journalist", "Media"]},
    {"word": "bad-deals", "categories": ["Politics"]},
    {"word": "california-train-project", "categories": ["Infrastructure", "Transportation"]},
    {"word": "nfl", "categories": ["Sports", "Football"]},
    {"word": "bakari-sellers", "categories": ["Person", "Political Commentator"]},
    {"word": "aaron-zebley", "categories": ["Person", "Legal"]},
    {"word": "super-bowl-50", "categories": ["Sports", "Football"]},
    {"word": "us-trade-representatives", "categories": ["Government", "Trade"]},
    {"word": "republicans", "categories": ["Political Party"]},
    {"word": "cdc", "categories": ["Organization", "Health"]},
    {"word": "manafort-sentence", "categories": ["Legal"]},
    {"word": "cbs", "categories": ["Media", "TV Network"]},
    {"word": "jon-ossoff", "categories": ["Politician", "Democrat"]},
    {"word": "veronica-escobar", "categories": ["Politician", "Democrat"]},
    {"word": "cruz-kasich-pact", "categories": ["Politics"]},
    {"word": "new-day", "categories": ["Media", "TV Show"]},
    {"word": "jeffrey-goldberg", "categories": ["Person", "Journalist"]},
    {"word": "robert-gates", "categories": ["Person", "Military"]},
    {"word": "hunter-biden", "categories": ["Person"]},
    {"word": "gonzalo-curiel", "categories": ["Person", "Legal"]},
    {"word": "pollsters", "categories": ["Politics"]},
    {"word": "atlantic-article-about-cemetery-comments", "categories": ["Media", "Article"]},
    {"word": "us-court-system", "categories": ["Legal"]},
    {"word": "cheri-jacobus", "categories": ["Person", "Political Commentator"]},
    {"word": "mark-halperin", "categories": ["Person", "Journalist"]},
    {"word": "tallahassee", "categories": ["City"]},
    {"word": "nbc-news", "categories": ["Media", "News Outlet"]},
    {"word": "illinois", "categories": ["State"]},
    {"word": "us-government", "categories": ["Government"]},
    {"word": "past-presidential-administrations", "categories": ["Politics", "History"]},
    {"word": "common-core", "categories": ["Education"]},
    {"word": "kweisi-mfume", "categories": ["Politician", "Democrat"]},
    {"word": "levar-ball", "categories": ["Person", "Sports"]},
    {"word": "theresa-greenfield", "categories": ["Politician", "Democrat"]},
    {"word": "hamilton-cast", "categories": ["Entertainment", "Theater"]},
    {"word": "michael-nutter", "categories": ["Politician", "Democrat"]},
    {"word": "john-allen", "categories": ["Person", "Military"]},
    {"word": "china", "categories": ["Country"]},
    {"word": "trump-critics", "categories": ["Politics"]},
    {"word": "ralph-northam", "categories": ["Politician", "Governor"]},
    {"word": "dan-henninger", "categories": ["Person", "Journalist"]},
    {"word": "obama-justice-department", "categories": ["Politics", "Legal"]},
    {"word": "legal-system", "categories": ["Legal"]},
    {"word": "fcc", "categories": ["Government", "Regulation"]},
    {"word": "md-7", "categories": ["State"]},
    {"word": "wsj-nbc-poll", "categories": ["Media", "Polls"]},
    {"word": "pulitzer-prizes", "categories": ["Media", "Awards"]},
    {"word": "iowa-caucus-2020", "categories": ["Politics", "Elections"]},
    {"word": "andrew-napolitano", "categories": ["Person", "Legal"]},
    {"word": "gitmo-prisoner-release", "categories": ["Legal", "Military"]},
    {"word": "laurene-powell-jobs", "categories": ["Person", "Business"]},
    {"word": "lisa-murkowski", "categories": ["Politician", "Republican"]},
    {"word": "democratic-disaster-bill", "categories": ["Politics", "Legislation"]},
    {"word": "tavis-smiley", "categories": ["Person", "Media"]},
    {"word": "refugees-in-germany", "categories": ["International Relations", "Refugees"]},
    {"word": "congress", "categories": ["Government"]},
    {"word": "christopher-steele", "categories": ["Person", "Politics"]},
    {"word": "biden-administration", "categories": ["Politics"]},
    {"word": "melinda-henneberger", "categories": ["Person", "Journalist"]},
    {"word": "immigration-lottery-system", "categories": ["Immigration"]},
    {"word": "hallie-jackson", "categories": ["Journalist", "Media"]},
    {"word": "jeb-bush-campaign", "categories": ["Politician", "Republican"]}
  ]
}
"""
group3 = """{
  "words": [
    {"word": "john-legere", "categories": ["Person", "Business"]},
    {"word": "virginia-economy", "categories": ["Economy", "State"]},
    {"word": "north-korea-experts", "categories": ["International Relations", "Experts"]},
    {"word": "comcast", "categories": ["Company", "Media"]},
    {"word": "howard-schultz", "categories": ["Person", "Business"]},
    {"word": "carl-d-leonnig", "categories": ["Person", "Journalist"]},
    {"word": "aoc", "categories": ["Politician", "Democrat"]},
    {"word": "justin-trudeau", "categories": ["Politician", "Prime Minister"]},
    {"word": "stephen-colbert", "categories": ["Person", "Entertainment"]},
    {"word": "us-australia-refugee-deal", "categories": ["International Relations", "Refugees"]},
    {"word": "maureen-dowd", "categories": ["Person", "Journalist"]},
    {"word": "steve-scully", "categories": ["Person", "Journalist"]},
    {"word": "anderson-cooper", "categories": ["Person", "Journalist"]},
    {"word": "beto-orourke", "categories": ["Politician", "Democrat"]},
    {"word": "erick-erickson", "categories": ["Person", "Conservative"]},
    {"word": "ted-cruz-iowa-speech", "categories": ["Politician", "Republican"]},
    {"word": "john-kasichs-ad-guy", "categories": ["Person", "Political Strategist"]},
    {"word": "goodyear-tires", "categories": ["Company", "Automotive"]},
    {"word": "frank-luntz", "categories": ["Person", "Political Consultant"]},
    {"word": "lovely-warren", "categories": ["Politician", "Mayor"]},
    {"word": "meghan-mccain", "categories": ["Person", "Media"]},
    {"word": "russell-moore", "categories": ["Person", "Religious Leader"]},
    {"word": "whistleblower-complaint", "categories": ["Legal", "Whistleblower"]},
    {"word": "mika-brzezinski", "categories": ["Person", "Journalist"]},
    {"word": "detroit", "categories": ["City"]},
    {"word": "special-interests", "categories": ["Politics"]},
    {"word": "section-230", "categories": ["Legal", "Technology"]},
    {"word": "george-pataki", "categories": ["Politician", "Republican"]},
    {"word": "debates", "categories": ["Politics"]},
    {"word": "ucla-basketball-players", "categories": ["Sports", "Basketball"]},
    {"word": "chris-coons", "categories": ["Politician", "Democrat"]},
    {"word": "nancy-pelosi", "categories": ["Politician", "Democrat"]},
    {"word": "david-gregory", "categories": ["Person", "Journalist"]},
    {"word": "mark-warner", "categories": ["Politician", "Democrat"]},
    {"word": "jacob-frey", "categories": ["Politician", "Mayor"]},
    {"word": "dnc-chairmanship-election", "categories": ["Politics", "Elections"]},
    {"word": "buzzfeed", "categories": ["Media", "News Outlet"]},
    {"word": "tom-steyer", "categories": ["Person", "Business"]},
    {"word": "anderson-cooper-360", "categories": ["Person", "Journalist"]},
    {"word": "nellie-ohr", "categories": ["Person", "Legal"]},
    {"word": "john-mccain", "categories": ["Person", "Politician"]},
    {"word": "big-game-hunting", "categories": ["Sports", "Hunting"]},
    {"word": "lawrence-o-donnell", "categories": ["Person", "Journalist"]},
    {"word": "jerome-powell", "categories": ["Person", "Economics"]},
    {"word": "jussie-smollet", "categories": ["Person", "Entertainment"]},
    {"word": "benghazi-hearings", "categories": ["Politics", "Investigations"]},
    {"word": "delegate-system", "categories": ["Politics", "Elections"]},
    {"word": "john-podesta", "categories": ["Person", "Politician"]},
    {"word": "us-intelligence-agencies", "categories": ["Government", "Intelligence"]},
    {"word": "debate-microphone", "categories": ["Politics", "Debates"]},
    {"word": "oreilly-factor", "categories": ["Media", "TV Show"]},
    {"word": "sadiq-khan", "categories": ["Politician", "Mayor"]},
    {"word": "kyrsten-sinema", "categories": ["Politician", "Democrat"]},
    {"word": "obama-administration", "categories": ["Politician", "Government"]},
    {"word": "yoel-roth", "categories": ["Person", "Social Media"]},
    {"word": "espn", "categories": ["Media", "Sports"]},
    {"word": "charles-blow", "categories": ["Person", "Journalist"]},
    {"word": "elizabeth-beck", "categories": ["Person", "Legal"]},
    {"word": "full-frontal", "categories": ["Media", "TV Show"]},
    {"word": "bill-maher", "categories": ["Person", "Entertainment"]},
    {"word": "trade-deals", "categories": ["Politics"]},
    {"word": "ben-sasse", "categories": ["Politician", "Republican"]},
    {"word": "spygate", "categories": ["Politics"]},
    {"word": "lisa-page", "categories": ["Person", "Legal"]},
    {"word": "john-kerry", "categories": ["Politician", "Democrat"]},
    {"word": "thomas-massie", "categories": ["Politician", "Republican"]},
    {"word": "maxine-waters", "categories": ["Politician", "Democrat"]},
    {"word": "voters", "categories": ["Politics"]},
    {"word": "bette-midler", "categories": ["Person", "Entertainment"]},
    {"word": "paul-singer", "categories": ["Person", "Business"]},
    {"word": "world-trade-organization", "categories": ["International Relations", "Economics"]},
    {"word": "impeachment-inquiry", "categories": ["Politics"]},
    {"word": "matthew-dowd", "categories": ["Person", "Journalist"]},
    {"word": "stone-judge", "categories": ["Person", "Legal"]},
    {"word": "harley-davidson", "categories": ["Company", "Automotive"]},
    {"word": "mitt-romney", "categories": ["Politician", "Republican"]},
    {"word": "max-rose", "categories": ["Politician", "Democrat"]},
    {"word": "katie-couric", "categories": ["Person", "Journalist"]},
    {"word": "state-of-the-union", "categories": ["Politics", "Speech"]},
    {"word": "bernard-goldberg", "categories": ["Person", "Journalist"]},
    {"word": "arrested-saudis", "categories": ["International Relations", "Legal"]},
    {"word": "alec-baldwin", "categories": ["Person", "Entertainment"]},
    {"word": "new-air-force-one", "categories": ["Government", "Aviation"]},
    {"word": "john-hickenlooper", "categories": ["Politician", "Democrat"]},
    {"word": "jb-pritzger", "categories": ["Politician", "Governor"]},
    {"word": "richard-blumenthal", "categories": ["Politician", "Democrat"]},
    {"word": "loretta-lynch", "categories": ["Person", "Legal"]},
    {"word": "polling-establishment", "categories": ["Politics", "Polls"]},
    {"word": "ana-navarro", "categories": ["Person", "Political Commentator"]},
    {"word": "milwaukee", "categories": ["City"]},
    {"word": "sherrod-brown", "categories": ["Politician", "Democrat"]},
    {"word": "mark-cuban", "categories": ["Person", "Business"]},
    {"word": "fbi", "categories": ["Government", "Law Enforcement"]},
    {"word": "puerto-rico", "categories": ["Territory"]},
    {"word": "dana-nessel", "categories": ["Person", "Legal"]},
    {"word": "abc-post-poll", "categories": ["Media", "Polls"]},
    {"word": "anthony-fauci", "categories": ["Person", "Health"]},
    {"word": "angela-merkel", "categories": ["Politician", "Chancellor"]},
    {"word": "states-refusing-to-give-voter-panel-info", "categories": ["Politics", "Elections"]},
    {"word": "jeb-staffer", "categories": ["Person", "Political Staff"]}
  ]
}
"""
group4 = """{
  "words": [
    {"word": "chris-wallace", "categories": ["Person", "Journalist"]},
    {"word": "jay-inslee", "categories": ["Politician", "Governor"]},
    {"word": "russia-bounty-story", "categories": ["International Relations", "News"]},
    {"word": "chris-krebs", "categories": ["Person", "Security"]},
    {"word": "the-room-where-it-happened", "categories": ["Book"]},
    {"word": "colin-kaepernick", "categories": ["Person", "Athlete"]},
    {"word": "fusion-gps", "categories": ["Company", "Political Research"]},
    {"word": "pakistan", "categories": ["Country"]},
    {"word": "george-papadopolous", "categories": ["Person", "Political Figure"]},
    {"word": "jocelyn-benson", "categories": ["Person", "Politician"]},
    {"word": "des-moines-register", "categories": ["Media", "Newspaper"]},
    {"word": "joe-donnely", "categories": ["Politician", "Democrat"]},
    {"word": "jennifer-rubin", "categories": ["Person", "Journalist"]},
    {"word": "hugh-hewitt", "categories": ["Person", "Media"]},
    {"word": "rockin-in-the-free-world", "categories": ["Music"]},
    {"word": "nascar", "categories": ["Sports", "Auto Racing"]},
    {"word": "nbc-executives", "categories": ["Company", "Media"]},
    {"word": "chris-cuomo", "categories": ["Person", "Journalist"]},
    {"word": "inside-politics", "categories": ["Media", "TV Show"]},
    {"word": "new-york", "categories": ["City"]},
    {"word": "the-new-yorker", "categories": ["Media", "Magazine"]},
    {"word": "california-cars", "categories": ["Automotive", "State"]},
    {"word": "john-dean", "categories": ["Person", "Legal"]},
    {"word": "gavin-newsom", "categories": ["Politician", "Governor"]},
    {"word": "jerry-brown", "categories": ["Politician", "Governor"]},
    {"word": "rinos-tk", "categories": ["Politics"]},
    {"word": "arianna-huffington", "categories": ["Person", "Media"]},
    {"word": "rick-scott", "categories": ["Politician", "Republican"]},
    {"word": "us-immigration-policies", "categories": ["Politics", "Immigration"]},
    {"word": "sweden", "categories": ["Country"]},
    {"word": "brian-stelter", "categories": ["Person", "Journalist"]},
    {"word": "rage-book", "categories": ["Book"]},
    {"word": "bandon-dunes", "categories": ["Sports", "Golf"]},
    {"word": "united-kingdom", "categories": ["Country"]},
    {"word": "twitter", "categories": ["Social Media"]},
    {"word": "political-ads-in-indiana", "categories": ["Politics", "Advertisements"]},
    {"word": "arnold-schwarzenegger", "categories": ["Person", "Actor"]},
    {"word": "epi-pens", "categories": ["Health", "Medicine"]},
    {"word": "william-weld", "categories": ["Person", "Politician"]},
    {"word": "nato", "categories": ["International Relations", "Organization"]},
    {"word": "jobs-report", "categories": ["Economy", "Report"]},
    {"word": "cory-booker", "categories": ["Politician", "Democrat"]},
    {"word": "barbara-underwood", "categories": ["Person", "Legal"]},
    {"word": "dean-baquet", "categories": ["Person", "Journalist"]},
    {"word": "minneapolis-looters", "categories": ["City", "Crime"]},
    {"word": "joy-behar", "categories": ["Person", "Entertainment"]},
    {"word": "ninth-circuit", "categories": ["Legal", "Court"]},
    {"word": "kirsten-gillibrand", "categories": ["Politician", "Democrat"]},
    {"word": "trump-opposition", "categories": ["Politics"]},
    {"word": "the-new-york-times", "categories": ["Media", "Newspaper"]},
    {"word": "union-leader", "categories": ["Media", "Newspaper"]},
    {"word": "saturday-night-live", "categories": ["Media", "TV Show"]},
    {"word": "vladimir-putin", "categories": ["Person", "Politician"]},
    {"word": "jon-tester", "categories": ["Politician", "Democrat"]},
    {"word": "marc-elias", "categories": ["Person", "Legal"]},
    {"word": "roger-goodell", "categories": ["Person", "Sports"]},
    {"word": "supreme-court-protestors", "categories": ["Legal", "Protest"]},
    {"word": "koch-brothers", "categories": ["Person", "Business"]},
    {"word": "john-roberts", "categories": ["Person", "Judge"]},
    {"word": "jimmy-kimmel", "categories": ["Person", "Entertainment"]},
    {"word": "mort-zuckerman", "categories": ["Person", "Business"]},
    {"word": "tim-kaine", "categories": ["Politician", "Democrat"]},
    {"word": "fbi-investigation-of-hillary", "categories": ["Politics", "Investigations"]},
    {"word": "george-will", "categories": ["Person", "Journalist"]},
    {"word": "fortune-magazine", "categories": ["Media", "Magazine"]},
    {"word": "stacey-abrams", "categories": ["Politician", "Democrat"]},
    {"word": "dem-convention-2020", "categories": ["Politics", "Event"]},
    {"word": "steve-kerr", "categories": ["Person", "Sports"]},
    {"word": "lesley-stahl", "categories": ["Person", "Journalist"]},
    {"word": "john-brennan", "categories": ["Person", "Government"]},
    {"word": "former-us-presidents", "categories": ["Politicians"]},
    {"word": "michael-deantonio", "categories": ["Person", "Author"]},
    {"word": "united-states", "categories": ["Country"]},
    {"word": "shephard-smith", "categories": ["Person", "Journalist"]},
    {"word": "richard-trumka", "categories": ["Person", "Union Leader"]},
    {"word": "drudge-report", "categories": ["Media", "Website"]},
    {"word": "anna-wintour", "categories": ["Person", "Fashion"]},
    {"word": "brad-raffensperger", "categories": ["Person", "Politician"]},
    {"word": "politically-correct-fools", "categories": ["Politics"]},
    {"word": "us-leaders", "categories": ["Politicians"]},
    {"word": "brian-kilmeade", "categories": ["Person", "Media"]},
    {"word": "vandals-in-nc", "categories": ["Crime"]},
    {"word": "repub-presidential-primary-challengers-2020", "categories": ["Politics"]},
    {"word": "bobby-jindal", "categories": ["Politician", "Republican"]},
    {"word": "biden-staff", "categories": ["Politics"]},
    {"word": "never-trumpers", "categories": ["Politics"]},
    {"word": "chuck-schumer", "categories": ["Politician", "Democrat"]},
    {"word": "chrissy-teigen", "categories": ["Person", "Entertainment"]},
    {"word": "nicole-wallace", "categories": ["Person", "Political Commentator"]},
    {"word": "prince-alwaleed-bin-talal", "categories": ["Person", "Business"]},
    {"word": "email-investigation", "categories": ["Politics"]},
    {"word": "rachel-maddow", "categories": ["Person", "Journalist"]},
    {"word": "willie-geist", "categories": ["Person", "Journalist"]},
    {"word": "obamagate", "categories": ["Politics"]},
    {"word": "other-republican-candidates", "categories": ["Politics"]},
    {"word": "john-roberts-fox", "categories": ["Person", "Journalist"]},
    {"word": "stefan-lofven", "categories": ["Politician", "Prime Minister"]},
    {"word": "doug-jones", "categories": ["Politician", "Democrat"]},
    {"word": "republican-candidates", "categories": ["Politics"]},
    {"word": "the-republican-establishment", "categories": ["Politics"]}
  ]
}
"""
group5 = """{
  "words": [
    {"word": "virginia-republican-party", "categories": ["Political Party", "State"]},
    {"word": "steve-bannon", "categories": ["Person", "Political Strategist"]},
    {"word": "joe-crowley", "categories": ["Person", "Politician"]},
    {"word": "cnn-international", "categories": ["Media", "TV Network"]},
    {"word": "chelsea-manning", "categories": ["Person", "Whistleblower"]},
    {"word": "bill-nelson", "categories": ["Person", "Politician"]},
    {"word": "auto-executives", "categories": ["Business", "Automotive"]},
    {"word": "pfizer", "categories": ["Company", "Pharmaceutical"]},
    {"word": "chris-hahn", "categories": ["Person", "Political Commentator"]},
    {"word": "team-of-vipers", "categories": ["Book"]},
    {"word": "marc-thiessen", "categories": ["Person", "Columnist"]},
    {"word": "juan-williams", "categories": ["Person", "Journalist"]},
    {"word": "democratic-national-committee", "categories": ["Political Organization"]},
    {"word": "late-night-television", "categories": ["Media", "TV Show"]},
    {"word": "paris-agreement", "categories": ["International Relations", "Climate"]},
    {"word": "debt-ceiling-approval", "categories": ["Politics", "Economy"]},
    {"word": "house-democrats", "categories": ["Politicians", "Democratic Party"]},
    {"word": "andy-lack", "categories": ["Person", "Media Executive"]},
    {"word": "hamilton", "categories": ["Entertainment", "Musical"]},
    {"word": "rick-wilson", "categories": ["Person", "Political Strategist"]},
    {"word": "karl-roves-book", "categories": ["Book"]},
    {"word": "late-night-television-hosts", "categories": ["Media", "TV Show"]},
    {"word": "ilhan-omar", "categories": ["Person", "Politician"]},
    {"word": "haywood-s-gilliam", "categories": ["Person", "Judge"]},
    {"word": "sam-nunberg", "categories": ["Person", "Political Consultant"]},
    {"word": "charles-koch", "categories": ["Person", "Business"]},
    {"word": "womens-assault-allegations", "categories": ["Social Issues", "Gender"]},
    {"word": "cnn-panelists", "categories": ["Media", "TV Show"]},
    {"word": "fbi-investigation-of-hillarys-emails", "categories": ["Politics", "Investigations"]},
    {"word": "very-stable-genius", "categories": ["Person", "Trump's Phrase"]},
    {"word": "flag-burners", "categories": ["Social Issues", "Protest"]},
    {"word": "ga-2020-recount", "categories": ["Politics", "Elections"]},
    {"word": "john-thune", "categories": ["Person", "Politician"]},
    {"word": "iran-deal", "categories": ["International Relations"]},
    {"word": "alisyn-camerota", "categories": ["Person", "Journalist"]},
    {"word": "brussels", "categories": ["City"]},
    {"word": "bloomberg-news", "categories": ["Media", "News"]},
    {"word": "democratic-house-committee", "categories": ["Politics", "Committee"]},
    {"word": "california", "categories": ["State"]},
    {"word": "carl-bernstein", "categories": ["Person", "Journalist"]},
    {"word": "larry-hogan", "categories": ["Politician", "Governor"]},
    {"word": "new-york-sea-wall", "categories": ["Infrastructure", "New York"]},
    {"word": "russia", "categories": ["Country"]},
    {"word": "samuel-l-jackson", "categories": ["Person", "Actor"]},
    {"word": "tsa", "categories": ["Government Agency", "Security"]},
    {"word": "chicago", "categories": ["City"]},
    {"word": "trump-report", "categories": ["Politics"]},
    {"word": "rodrigo-duterte", "categories": ["Person", "Politician"]},
    {"word": "david-kris", "categories": ["Person", "Legal"]},
    {"word": "germany", "categories": ["Country"]},
    {"word": "biden-ad", "categories": ["Politics", "Advertisements"]},
    {"word": "quinnipiac-polls", "categories": ["Polls"]},
    {"word": "michael-bloomberg", "categories": ["Person", "Business"]},
    {"word": "recounts-in-florida", "categories": ["Politics", "Elections"]},
    {"word": "rich-lowry", "categories": ["Person", "Journalist"]},
    {"word": "nafta", "categories": ["International Relations", "Trade"]},
    {"word": "joe-scarborough", "categories": ["Person", "TV Host"]},
    {"word": "pundits", "categories": ["Media", "Commentators"]},
    {"word": "brenda-snipes", "categories": ["Person", "Election Official"]},
    {"word": "maggie-haberman", "categories": ["Person", "Journalist"]},
    {"word": "politicians", "categories": ["Politicians"]},
    {"word": "erin-burnett", "categories": ["Person", "Journalist"]},
    {"word": "emmanuel-macron", "categories": ["Person", "Politician"]},
    {"word": "polls", "categories": ["Polls"]},
    {"word": "spike-lee", "categories": ["Person", "Director"]},
    {"word": "ruth-marcus-book", "categories": ["Book"]},
    {"word": "peter-baker", "categories": ["Person", "Journalist"]},
    {"word": "whoopi-goldberg", "categories": ["Person", "Entertainer"]},
    {"word": "wreath-cancellation-policy", "categories": ["Policy"]},
    {"word": "jeff-sessions", "categories": ["Person", "Politician"]},
    {"word": "jared-polis", "categories": ["Politician", "Governor"]},
    {"word": "protesters", "categories": ["Social Issues", "Protest"]},
    {"word": "ig-report", "categories": ["Politics", "Investigations"]},
    {"word": "david-cicilline", "categories": ["Person", "Politician"]},
    {"word": "the-clintons", "categories": ["Person", "Political Family"]},
    {"word": "peter-strzok", "categories": ["Person", "FBI Agent"]},
    {"word": "democrats-nunes-memo", "categories": ["Politics", "Memo"]},
    {"word": "stormy-daniels-alleged-assailant", "categories": ["Person", "Legal"]},
    {"word": "harry-hurt", "categories": ["Person", "Journalist"]},
    {"word": "mueller-report", "categories": ["Politics", "Investigations"]},
    {"word": "lincoln-chafee", "categories": ["Person", "Politician"]},
    {"word": "joe-biden", "categories": ["Person", "Politician"]},
    {"word": "baltimore", "categories": ["City"]},
    {"word": "lebron-james", "categories": ["Person", "Athlete"]},
    {"word": "omarosa-manigault", "categories": ["Person", "TV Personality"]},
    {"word": "kneeling-nfl-players", "categories": ["Sports", "Protest"]},
    {"word": "mueller-team", "categories": ["Politics", "Investigations"]},
    {"word": "robert-deniro", "categories": ["Person", "Actor"]},
    {"word": "paul-krugman", "categories": ["Person", "Economist"]},
    {"word": "dana-perino", "categories": ["Person", "TV Host"]},
    {"word": "meryl-streep", "categories": ["Person", "Actor"]},
    {"word": "muriel-bowser", "categories": ["Person", "Politician"]},
    {"word": "kate-brown", "categories": ["Person", "Governor"]},
    {"word": "rashida-tlaib", "categories": ["Person", "Politician"]},
    {"word": "ted-wheeler", "categories": ["Person", "Politician"]},
    {"word": "kathy-griffin", "categories": ["Person", "Comedian"]},
    {"word": "nsa", "categories": ["Government Agency"]},
    {"word": "elites", "categories": ["Social Issues"]},
    {"word": "hunter-bidens-laptop", "categories": ["Politics", "Scandal"]},
    {"word": "claire-mccaskill", "categories": ["Person", "Politician"]}
  ]
}
"""
group6 = """
{
  "words": [
    {"word": "canada", "categories": ["Country"]},
    {"word": "fda", "categories": ["Government Agency", "Health"]},
    {"word": "losers-haters", "categories": ["Social Issues", "Criticism"]},
    {"word": "caravans", "categories": ["Social Issues", "Immigration"]},
    {"word": "michelle-wolf", "categories": ["Person", "Comedian"]},
    {"word": "ken-frazier", "categories": ["Person", "Business"]},
    {"word": "rexnord", "categories": ["Company", "Manufacturing"]},
    {"word": "rick-snyder", "categories": ["Person", "Politician"]},
    {"word": "bob-woodward", "categories": ["Person", "Journalist"]},
    {"word": "jamie-dimon", "categories": ["Person", "Business"]},
    {"word": "commission-on-presidential-debates", "categories": ["Organization", "Debates"]},
    {"word": "pharma-ad", "categories": ["Advertising", "Pharmaceutical"]},
    {"word": "al-sharpton", "categories": ["Person", "Activist"]},
    {"word": "frank-vandersloot", "categories": ["Person", "Business"]},
    {"word": "brett-mcgurk", "categories": ["Person", "Government"]},
    {"word": "rex-tillerson", "categories": ["Person", "Government"]},
    {"word": "manufacturing-ceos", "categories": ["Business", "Manufacturing"]},
    {"word": "catch-and-release", "categories": ["Social Issues", "Immigration"]},
    {"word": "iowa-democratic-party", "categories": ["Political Party", "State"]},
    {"word": "evan-mcmullin", "categories": ["Person", "Politician"]},
    {"word": "2016-election", "categories": ["Politics", "Elections"]},
    {"word": "paulina-vega", "categories": ["Person", "Beauty Queen"]},
    {"word": "paul-begala", "categories": ["Person", "Political Consultant"]},
    {"word": "forbes", "categories": ["Media", "Magazine"]},
    {"word": "scott-walker", "categories": ["Person", "Politician"]},
    {"word": "vanity-fair", "categories": ["Media", "Magazine"]},
    {"word": "dianne-feinstein", "categories": ["Person", "Politician"]},
    {"word": "pete-ricketts", "categories": ["Person", "Governor"]},
    {"word": "snoop-dogg", "categories": ["Person", "Musician"]},
    {"word": "frank-bruni", "categories": ["Person", "Journalist"]},
    {"word": "george-h-w-bush", "categories": ["Person", "President"]},
    {"word": "mary-trump", "categories": ["Person", "Family Member"]},
    {"word": "woody-johnson", "categories": ["Person", "Business"]},
    {"word": "gretchen-whitmer", "categories": ["Person", "Governor"]},
    {"word": "palestine", "categories": ["Country"]},
    {"word": "el-salvador", "categories": ["Country"]},
    {"word": "the-oscars", "categories": ["Entertainment", "Awards"]},
    {"word": "comcast-executives", "categories": ["Company", "Media"]},
    {"word": "al-franken", "categories": ["Person", "Politician"]},
    {"word": "michael-avenatti", "categories": ["Person", "Lawyer"]},
    {"word": "joe-manchin", "categories": ["Person", "Politician"]},
    {"word": "amy-klobuchar", "categories": ["Person", "Politician"]},
    {"word": "us-legal-system", "categories": ["Legal", "System"]},
    {"word": "mike-pence", "categories": ["Person", "Vice President"]},
    {"word": "super-pacs", "categories": ["Politics", "Campaign Finance"]},
    {"word": "gm-plant-ohio", "categories": ["Business", "Manufacturing"]},
    {"word": "bob-vander-plaats", "categories": ["Person", "Activist"]},
    {"word": "mccabe-memos", "categories": ["Person", "Government"]},
    {"word": "chemical-attack-syria", "categories": ["Politics", "International Relations"]},
    {"word": "amy-chozick", "categories": ["Person", "Journalist"]},
    {"word": "honduras", "categories": ["Country"]},
    {"word": "vote-count-michigan", "categories": ["Politics", "Elections"]},
    {"word": "george-conway", "categories": ["Person", "Lawyer"]},
    {"word": "french-wine", "categories": ["Food and Drink", "Wine"]},
    {"word": "theresa-may", "categories": ["Person", "Politician"]},
    {"word": "eddie-johnson", "categories": ["Person", "Police"]},
    {"word": "jeff-horwitz", "categories": ["Person", "Journalist"]},
    {"word": "carly-fiorina", "categories": ["Person", "Business"]},
    {"word": "boston-globe", "categories": ["Media", "Newspaper"]},
    {"word": "macys", "categories": ["Company", "Retail"]},
    {"word": "the-view", "categories": ["Media", "TV Show"]},
    {"word": "seattle-portland-protesters", "categories": ["Social Issues", "Protests"]},
    {"word": "ruth-marcus", "categories": ["Person", "Journalist"]},
    {"word": "national-review", "categories": ["Media", "Magazine"]},
    {"word": "the-courts", "categories": ["Legal", "Courts"]},
    {"word": "anthony-scaramucci", "categories": ["Person", "Business"]},
    {"word": "mitch-mcconnell", "categories": ["Person", "Politician"]},
    {"word": "neil-young", "categories": ["Person", "Musician"]},
    {"word": "john-harwood", "categories": ["Person", "Journalist"]},
    {"word": "roger-stone-sentence", "categories": ["Person", "Legal"]},
    {"word": "letitia-james", "categories": ["Person", "Attorney General"]},
    {"word": "karen-bass", "categories": ["Person", "Politician"]},
    {"word": "lindsey-graham", "categories": ["Person", "Politician"]},
    {"word": "richard-cordray", "categories": ["Person", "Government"]},
    {"word": "new-york-democrats", "categories": ["Political Party", "State"]},
    {"word": "coronavirus", "categories": ["Health", "Pandemic"]},
    {"word": "tpp-deal", "categories": ["Politics", "Trade"]},
    {"word": "florida-early-voting", "categories": ["Politics", "Elections"]},
    {"word": "the-establishment", "categories": ["Politics", "System"]},
    {"word": "gustavo-petro", "categories": ["Person", "Politician"]},
    {"word": "democratic-national-convention", "categories": ["Political Party", "Event"]},
    {"word": "jeb-bush", "categories": ["Person", "Politician"]},
    {"word": "rnc", "categories": ["Political Party", "Event"]},
    {"word": "trump-russia", "categories": ["Politics", "Investigations"]},
    {"word": "susan-rice", "categories": ["Person", "Politician"]},
    {"word": "ali-khamenei", "categories": ["Person", "Religious Leader"]},
    {"word": "julian-castro", "categories": ["Person", "Politician"]},
    {"word": "pennsylvania", "categories": ["State"]},
    {"word": "brian-ross", "categories": ["Person", "Journalist"]},
    {"word": "james-robart", "categories": ["Person", "Judge"]},
    {"word": "greta-thunberg", "categories": ["Person", "Activist"]},
    {"word": "small-wall-section", "categories": ["Politics", "Immigration"]},
    {"word": "richard-goodstein", "categories": ["Person", "Political Consultant"]},
    {"word": "debbie-wasserman-schultz", "categories": ["Person", "Politician"]},
    {"word": "kamala-harris", "categories": ["Person", "Politician"]},
    {"word": "comey-memos", "categories": ["Person", "Government"]},
    {"word": "water-lanes", "categories": ["Politics", "Infrastructure"]},
    {"word": "mueller-hearings", "categories": ["Politics", "Investigations"]},
    {"word": "wisconsin-recount", "categories": ["Politics", "Elections"]},
    {"word": "seth-meyers", "categories": ["Person", "Comedian"]}
  ]
}
"""
group7 = """
{
  "words": [
    {"word": "la-dodgers-relievers", "categories": ["Sports", "Baseball"]},
    {"word": "drug-cartels", "categories": ["Crime", "Drug Trade"]},
    {"word": "jennifer-griffin", "categories": ["Person", "Journalist"]},
    {"word": "2020-dem-candidates", "categories": ["Politics", "Elections"]},
    {"word": "philadelphia", "categories": ["City"]},
    {"word": "supporters-of-middle-east-wars", "categories": ["Politics", "War"]},
    {"word": "first-100-days", "categories": ["Politics", "Government"]},
    {"word": "joe-walsh", "categories": ["Person", "Politician"]},
    {"word": "brit-hume", "categories": ["Person", "Journalist"]},
    {"word": "club-for-growth", "categories": ["Organization", "Economic Policy"]},
    {"word": "democratic-debate-july-30", "categories": ["Politics", "Debates"]},
    {"word": "tom-ridge", "categories": ["Person", "Politician"]},
    {"word": "political-ads", "categories": ["Politics", "Advertising"]},
    {"word": "michael-moore-show", "categories": ["Media", "TV Show"]},
    {"word": "presidential-candidates", "categories": ["Politics", "Elections"]},
    {"word": "ronda-rousey", "categories": ["Person", "Athlete"]},
    {"word": "anthony-weiner", "categories": ["Person", "Politician"]},
    {"word": "kate-steinle-verdict", "categories": ["Legal", "Verdict"]},
    {"word": "anne-karni", "categories": ["Person", "Journalist"]},
    {"word": "andrew-mccabe", "categories": ["Person", "Government"]},
    {"word": "the-squad", "categories": ["Politics", "Group"]},
    {"word": "single-payer-health-plan", "categories": ["Politics", "Healthcare"]},
    {"word": "thomas-frieden", "categories": ["Person", "Government"]},
    {"word": "amazon", "categories": ["Company", "Retail"]},
    {"word": "intelligence-leakers", "categories": ["Politics", "Security"]},
    {"word": "scotus-rally", "categories": ["Politics", "Protests"]},
    {"word": "town-hall-meetings", "categories": ["Politics", "Events"]},
    {"word": "weekly-standard", "categories": ["Media", "Magazine"]},
    {"word": "jeff-flake", "categories": ["Person", "Politician"]},
    {"word": "eric-swalwell", "categories": ["Person", "Politician"]},
    {"word": "calif-12", "categories": ["Politics", "District"]},
    {"word": "alexander-vindman", "categories": ["Person", "Government"]},
    {"word": "states-with-dem-governors", "categories": ["Politics", "Governors"]},
    {"word": "peggy-noonan", "categories": ["Person", "Journalist"]},
    {"word": "red-state", "categories": ["Politics", "State"]},
    {"word": "anti-trump-ads", "categories": ["Politics", "Advertising"]},
    {"word": "bruce-ohr", "categories": ["Person", "Government"]},
    {"word": "usps", "categories": ["Organization", "Postal Service"]},
    {"word": "trumps-taxes", "categories": ["Politics", "Taxation"]},
    {"word": "undocumented-immigrants", "categories": ["Politics", "Immigration"]},
    {"word": "fox-news-sunday", "categories": ["Media", "TV Show"]},
    {"word": "harry-reid", "categories": ["Person", "Politician"]},
    {"word": "james-comey", "categories": ["Person", "Government"]},
    {"word": "john-kasich", "categories": ["Person", "Politician"]},
    {"word": "james-clyburn", "categories": ["Person", "Politician"]},
    {"word": "oval-office-podium", "categories": ["Politics", "Government"]},
    {"word": "london", "categories": ["City"]},
    {"word": "s-e-cupp", "categories": ["Person", "Journalist"]},
    {"word": "donna-brazile", "categories": ["Person", "Political Strategist"]},
    {"word": "state-department", "categories": ["Organization", "Government"]},
    {"word": "democratic-debate", "categories": ["Politics", "Debates"]},
    {"word": "pledge-of-allegiance-decision-slp", "categories": ["Legal", "Decision"]},
    {"word": "jamie-weinstein", "categories": ["Person", "Journalist"]},
    {"word": "leakers", "categories": ["Politics", "Security"]},
    {"word": "ted-cruz-campaign", "categories": ["Politics", "Campaign"]},
    {"word": "megan-rapinoe", "categories": ["Person", "Athlete"]},
    {"word": "politico", "categories": ["Media", "Website"]},
    {"word": "fox-news-debate", "categories": ["Media", "TV Show"]},
    {"word": "filibuster-rule", "categories": ["Politics", "Government"]},
    {"word": "nevada", "categories": ["State"]},
    {"word": "ben-carson", "categories": ["Person", "Politician"]},
    {"word": "whca-dinner", "categories": ["Politics", "Event"]},
    {"word": "tom-llamas", "categories": ["Person", "Journalist"]},
    {"word": "elijah-cummings", "categories": ["Person", "Politician"]},
    {"word": "justin-amash", "categories": ["Person", "Politician"]},
    {"word": "the-system", "categories": ["Politics", "Government"]},
    {"word": "wall-of-moms", "categories": ["Social Issues", "Protests"]},
    {"word": "univision", "categories": ["Media", "TV Network"]},
    {"word": "michael-wolff", "categories": ["Person", "Author"]},
    {"word": "mark-sanford", "categories": ["Person", "Politician"]},
    {"word": "democrat-run-states", "categories": ["Politics", "State"]},
    {"word": "chuck-todd", "categories": ["Person", "Journalist"]},
    {"word": "john-lewis", "categories": ["Person", "Politician"]},
    {"word": "joy-ann-reid", "categories": ["Person", "Journalist"]},
    {"word": "nbc", "categories": ["Media", "TV Network"]},
    {"word": "ca-28", "categories": ["Politics", "District"]},
    {"word": "endless-wars", "categories": ["Politics", "War"]},
    {"word": "2020-pres-debate??", "categories": ["Politics", "Debates"]},
    {"word": "dc-leaders?", "categories": ["Politics", "Government"]},
    {"word": "dc-police", "categories": ["Organization", "Law Enforcement"]},
    {"word": "blm-protesters", "categories": ["Social Issues", "Protests"]},
    {"word": "iran", "categories": ["Country"]},
    {"word": "geoff-duncan", "categories": ["Person", "Politician"]},
    {"word": "draghi-stimulus-remarks", "categories": ["Economics", "Remarks"]},
    {"word": "ronald-klain", "categories": ["Person", "Government"]},
    {"word": "anthony-brindisi", "categories": ["Person", "Politician"]},
    {"word": "brandon-victor-dixon", "categories": ["Person", "Actor"]},
    {"word": "cnn-polls", "categories": ["Media", "Polling"]},
    {"word": "clare-o-connor", "categories": ["Person", "Journalist"]},
    {"word": "donna-shalala", "categories": ["Person", "Politician"]},
    {"word": "matt-bai", "categories": ["Person", "Journalist"]},
    {"word": "atlanta", "categories": ["City"]},
    {"word": "juaquin-castro", "categories": ["Person", "Politician"]},
    {"word": "ben-schreckenger", "categories": ["Person", "Journalist"]},
    {"word": "today-show", "categories": ["Media", "TV Show"]},
    {"word": "bill-kristol", "categories": ["Person", "Political Commentator"]},
    {"word": "norah-o-donnell", "categories": ["Person", "Journalist"]},
    {"word": "bob-casey", "categories": ["Person", "Politician"]},
    {"word": "decision-to-disqualify-horse", "categories": ["Sports", "Horse Racing"]},
    {"word": "errol-louis", "categories": ["Person", "Journalist"]}
  ]
}
"""
group8 = """
{
  "words": [
    {"word": "glenn-beck", "categories": ["Person", "Media Personality"]},
    {"word": "jemele-hill", "categories": ["Person", "Journalist"]},
    {"word": "portland", "categories": ["City"]},
    {"word": "nonsupporting-republicans", "categories": ["Politics", "Republicans"]},
    {"word": "uk-ambassador", "categories": ["Politics", "Diplomacy"]},
    {"word": "2020-election", "categories": ["Politics", "Elections"]},
    {"word": "debbie-stabenow", "categories": ["Person", "Politician"]},
    {"word": "afl-cio", "categories": ["Organization", "Labor Union"]},
    {"word": "daca-kids", "categories": ["Politics", "Immigration"]},
    {"word": "huma-abedin", "categories": ["Person", "Political Figure"]},
    {"word": "joe-mcquaid", "categories": ["Person", "Journalist"]},
    {"word": "washington-insiders", "categories": ["Politics", "Insiders"]},
    {"word": "sally-yates", "categories": ["Person", "Government"]},
    {"word": "united-steelworkers", "categories": ["Organization", "Labor Union"]},
    {"word": "pramila-jayapal", "categories": ["Person", "Politician"]},
    {"word": "morning-joe", "categories": ["Media", "TV Show"]},
    {"word": "john-king", "categories": ["Person", "Journalist"]},
    {"word": "tammy-baldwin", "categories": ["Person", "Politician"]},
    {"word": "cliff-sims", "categories": ["Person", "Author"]},
    {"word": "general-motors", "categories": ["Company", "Automotive"]},
    {"word": "nate-silver", "categories": ["Person", "Statistician"]},
    {"word": "south-bend", "categories": ["City"]},
    {"word": "the-red-hen", "categories": ["Business", "Restaurant"]},
    {"word": "senate-republicans", "categories": ["Politics", "Republicans"]},
    {"word": "firefighters-union", "categories": ["Organization", "Labor Union"]},
    {"word": "katie-rogers", "categories": ["Person", "Journalist"]},
    {"word": "usa-today", "categories": ["Media", "Newspaper"]},
    {"word": "mary-katharine-ham", "categories": ["Person", "Journalist"]},
    {"word": "mark-herring", "categories": ["Person", "Politician"]},
    {"word": "dnc", "categories": ["Organization", "Political Party"]},
    {"word": "alleged-nyc-terrorist", "categories": ["Crime", "Terrorism"]},
    {"word": "john-oliver", "categories": ["Person", "Comedian"]},
    {"word": "ny-prosecutors", "categories": ["Organization", "Legal"]},
    {"word": "big-tech", "categories": ["Business", "Technology"]},
    {"word": "california-water-use", "categories": ["Politics", "Environment"]},
    {"word": "major-garrett", "categories": ["Person", "Journalist"]},
    {"word": "rick-bright", "categories": ["Person", "Government"]},
    {"word": "nikki-haley", "categories": ["Person", "Politician"]},
    {"word": "michael-morell", "categories": ["Person", "Government"]},
    {"word": "stephen-hahn", "categories": ["Person", "Government"]},
    {"word": "jerry-nadler", "categories": ["Person", "Politician"]},
    {"word": "mail-in-voting", "categories": ["Politics", "Voting"]},
    {"word": "carl-cameron", "categories": ["Person", "Journalist"]},
    {"word": "carmen-yulin-cruz", "categories": ["Person", "Politician"]},
    {"word": "steve-schmidt", "categories": ["Person", "Political Strategist"]},
    {"word": "kristen-welker", "categories": ["Person", "Journalist"]},
    {"word": "democratic-candidates", "categories": ["Politics", "Elections"]},
    {"word": "puerto-rico-infrastructure", "categories": ["Politics", "Infrastructure"]},
    {"word": "emmys-2017", "categories": ["Media", "Awards"]},
    {"word": "deb-sopan", "categories": ["Person", "Journalist"]},
    {"word": "facebook", "categories": ["Company", "Social Media"]},
    {"word": "philip-rucker", "categories": ["Person", "Journalist"]},
    {"word": "department-of-justice", "categories": ["Organization", "Legal"]},
    {"word": "stephanie-rawlings-blake", "categories": ["Person", "Politician"]},
    {"word": "bill-clinton", "categories": ["Person", "Former President"]},
    {"word": "conor-lamb", "categories": ["Person", "Politician"]},
    {"word": "ca-25-election", "categories": ["Politics", "Elections"]},
    {"word": "strzok-page-texts", "categories": ["Politics", "Texts"]},
    {"word": "schiff-memo", "categories": ["Politics", "Memo"]},
    {"word": "bias-free-language-guide", "categories": ["Politics", "Language"]},
    {"word": "elizabeth-warren", "categories": ["Person", "Politician"]},
    {"word": "senate-democrats", "categories": ["Politics", "Democrats"]},
    {"word": "ben-cardin", "categories": ["Person", "Politician"]},
    {"word": "lisa-belkin", "categories": ["Person", "Journalist"]},
    {"word": "chuck-jones", "categories": ["Person", "Labor Leader"]},
    {"word": "james-clapper", "categories": ["Person", "Government"]},
    {"word": "sanctuary-cities", "categories": ["Politics", "Cities"]},
    {"word": "nordstrom", "categories": ["Business", "Retail"]},
    {"word": "california-environmental-laws", "categories": ["Politics", "Environment"]},
    {"word": "san-francisco", "categories": ["City"]},
    {"word": "green-new-deal", "categories": ["Politics", "Environment"]},
    {"word": "judge-appointments-delay-tactics", "categories": ["Politics", "Judiciary"]},
    {"word": "sarah-jeong", "categories": ["Person", "Journalist"]},
    {"word": "joe-cunningham", "categories": ["Person", "Politician"]},
    {"word": "larry-sabato", "categories": ["Person", "Political Analyst"]},
    {"word": "paul-ryan", "categories": ["Person", "Politician"]},
    {"word": "people", "categories": ["General Term"]},
    {"word": "marshawn-lynch", "categories": ["Person", "Athlete"]},
    {"word": "opec", "categories": ["Organization", "Oil"]},
    {"word": "jenny-durkan", "categories": ["Person", "Politician"]},
    {"word": "internal-revenue-service", "categories": ["Organization", "Government"]},
    {"word": "jim-mattis", "categories": ["Person", "Government"]},
    {"word": "kim-jong-un", "categories": ["Person", "Politician"]},
    {"word": "bashar-al-assad", "categories": ["Person", "Politician"]},
    {"word": "north-korea", "categories": ["Country"]},
    {"word": "southern-border", "categories": ["Politics", "Borders"]},
    {"word": "world-news-tonight", "categories": ["Media", "TV Show"]},
    {"word": "stuart-stevens", "categories": ["Person", "Political Consultant"]},
    {"word": "debbie-dingell", "categories": ["Person", "Politician"]},
    {"word": "david-cay-johnston", "categories": ["Person", "Journalist"]},
    {"word": "face-the-nation", "categories": ["Media", "TV Show"]},
    {"word": "harley-rouda", "categories": ["Person", "Politician"]},
    {"word": "dave-weigel", "categories": ["Person", "Journalist"]},
    {"word": "nc-ballot-extension", "categories": ["Politics", "Elections"]},
    {"word": "civil-war-memorial-opponents", "categories": ["Politics", "Memorials"]},
    {"word": "the-fed", "categories": ["Organization", "Economics"]},
    {"word": "headline", "categories": ["Media", "News"]},
    {"word": "illegal-leaks", "categories": ["Politics", "Leaks"]},
    {"word": "antifa", "categories": ["Organization", "Protest Movement"]},
    {"word": "illegal-immigration", "categories": ["Politics", "Immigration"]}
  ]
}"""
group9 = """
{
  "words": [
    {"word": "kasie-hunt", "categories": ["Person", "Journalist"]},
    {"word": "travel-ban", "categories": ["Politics", "Immigration"]},
    {"word": "abc-news", "categories": ["Media", "News Network"]},
    {"word": "ashley-parker", "categories": ["Person", "Journalist"]},
    {"word": "mikie-sherrill", "categories": ["Person", "Politician"]},
    {"word": "jeff-zucker", "categories": ["Person", "Media Executive"]},
    {"word": "michael-cohen", "categories": ["Person", "Lawyer"]},
    {"word": "jimmy-fallon", "categories": ["Person", "Comedian"]},
    {"word": "biden-family", "categories": ["Person", "Family"]},
    {"word": "stone-juror", "categories": ["Person", "Juror"]},
    {"word": "the-individual-mandate", "categories": ["Politics", "Healthcare"]},
    {"word": "mayor-pete", "categories": ["Person", "Politician"]},
    {"word": "decision-to-halt-the-ban", "categories": ["Politics", "Immigration"]},
    {"word": "clinton-foundation", "categories": ["Organization", "Charity"]},
    {"word": "cnbc", "categories": ["Media", "News Network"]},
    {"word": "don-lemon", "categories": ["Person", "Journalist"]},
    {"word": "justin-fairfax", "categories": ["Person", "Politician"]},
    {"word": "nytimes-article", "categories": ["Media", "Newspaper"]},
    {"word": "john-bel-edwards", "categories": ["Person", "Politician"]},
    {"word": "books-critical-of-president-trump", "categories": ["Media", "Books"]},
    {"word": "bitcoin", "categories": ["Business", "Cryptocurrency"]},
    {"word": "us-korea-military-exercises", "categories": ["Politics", "Military"]},
    {"word": "abc-politics", "categories": ["Media", "Politics"]},
    {"word": "john-sununu", "categories": ["Person", "Politician"]},
    {"word": "associated-press", "categories": ["Media", "News Agency"]},
    {"word": "guatemala", "categories": ["Country"]},
    {"word": "puerto-rico-aid-relief", "categories": ["Politics", "Aid"]},
    {"word": "pat-toomey", "categories": ["Person", "Politician"]},
    {"word": "ann-coulter", "categories": ["Person", "Commentator"]},
    {"word": "david-brooks", "categories": ["Person", "Journalist"]},
    {"word": "dave-roberts", "categories": ["Person", "Athlete"]},
    {"word": "charlie-baker", "categories": ["Person", "Politician"]},
    {"word": "sam-liccardo", "categories": ["Person", "Politician"]},
    {"word": "ga-2020-vote", "categories": ["Politics", "Elections"]},
    {"word": "ruth-bader-ginsburg", "categories": ["Person", "Justice"]},
    {"word": "frederica-wilson", "categories": ["Person", "Politician"]},
    {"word": "serge-kovaleski", "categories": ["Person", "Journalist"]},
    {"word": "jeff-zeleny", "categories": ["Person", "Journalist"]},
    {"word": "the-last-word-with-lawrence-o-donnell", "categories": ["Media", "TV Show"]},
    {"word": "jill-colvin", "categories": ["Person", "Journalist"]},
    {"word": "laws-about-sanctuary-cities", "categories": ["Politics", "Cities"]},
    {"word": "fire-and-fury", "categories": ["Media", "Book"]},
    {"word": "andrew-cuomo", "categories": ["Person", "Politician"]},
    {"word": "christianity-today", "categories": ["Media", "Magazine"]},
    {"word": "dominion-voting", "categories": ["Business", "Voting Systems"]},
    {"word": "cokie-roberts", "categories": ["Person", "Journalist"]},
    {"word": "cfpb", "categories": ["Organization", "Government"]},
    {"word": "lincoln-project", "categories": ["Organization", "Political Action Committee"]},
    {"word": "freedom-caucus", "categories": ["Organization", "Political Group"]},
    {"word": "wall-street-journal", "categories": ["Media", "Newspaper"]},
    {"word": "michael-barbaro", "categories": ["Person", "Journalist"]},
    {"word": "brian-kemp", "categories": ["Person", "Politician"]},
    {"word": "nba", "categories": ["Organization", "Sports League"]},
    {"word": "new-york-city", "categories": ["City"]},
    {"word": "veterans-affairs", "categories": ["Organization", "Government"]},
    {"word": "meet-the-press", "categories": ["Media", "TV Show"]},
    {"word": "the-atlantic", "categories": ["Media", "Magazine"]},
    {"word": "barack-obama", "categories": ["Person", "Politician"]},
    {"word": "michael-flynn-case", "categories": ["Person", "Legal Case"]},
    {"word": "matt-drudge", "categories": ["Person", "Journalist"]},
    {"word": "fox-news", "categories": ["Media", "News Network"]},
    {"word": "john-bolton", "categories": ["Person", "Politician"]},
    {"word": "bernie-sanders", "categories": ["Person", "Politician"]},
    {"word": "marty-walsh", "categories": ["Person", "Politician"]},
    {"word": "f35-program", "categories": ["Military", "Aircraft"]},
    {"word": "huffington-post", "categories": ["Media", "News Website"]}
  ]
}
"""
