trump_classification = {'john-kelly': ['Military Personnel'], 'nbc-nightly-news': ['Media', 'TV Show', 'News'],
     'brent-bozell': ['Conservative Personnel'], 'looters': ['Social Issues', 'Crime'],
     'martin-o-malley': ['Politician', 'Democrat'], 'oprah-winfrey': ['Entertainment Personnel'],
     'marco-rubio': ['Politician', 'Republican'], 'jim-acosta': ['Journalist', 'Media', 'CNN'], 'mexico': ['Country'],
     't-mobile': ['Company', 'Technology'], 'us-mexico-trade-surplus': ['Economy', 'Trade'],
     'andrew-weissmann': ['Legal Personnel'], 'saudi-arabia': ['Country'], 'jackson-lee': ['Politician', 'Democrat'],
     'h1n1-response': ['Health', 'Pandemic'], 'rand-paul': ['Politician', 'Republican'],
     'steve-rattner': ['Finance Personnel'], 'fox-news-polls': ['Media', 'Polls'], 'tim-o-brien': ['Author'],
     'chris-christie': ['Politician', 'Republican'], 'katy-tur': ['Journalist', 'Media'],
     'karl-rove': ['Political Strategist'], 'rod-rosenstein': ['Legal Personnel'], 'los-angeles': ['City'],
     'european-leaders': ['International Relations', 'Leadership'], 'george-w-bush': ['Politician'],
     'social-media': ['Technology', 'Social Issues'], 'major-league-baseball': ['Sports', 'Baseball'],
     'tom-friedman': ['Journalist Personnel'], 'woodward-book': ['Book', 'Author'],
     'miles-taylor': ['Government Personnel'],
     'democrats': ['Political Party'], 'nbc-polls': ['Media', 'Polls'], 'ms-13': ['Criminal Organization'],
     'samantha-bee': ['Entertainment', 'Comedian'], 'the-haters': ['Social Issues'], 'john-huber': ['Legal Personnel'],
     'danny-o-connor': ['Politician', 'Democrat'], 'cynthia-nixon': ['Actor'],
     'colin-powell': ['Politician'], 'who': ['Organization', 'Health'], 'turkey': ['Country'],
     'philip-mudd': ['Political Commentator'], '???': ['Uncategorized'], 'tony-podesta': ['Lobbyist'],
     'daily-beast': ['Media', 'News Outlet'], 'al-schmidt': ['Politician', 'Republican'],
     'dan-mccready': ['Politician', 'Democrat'],
     'puerto-ricans': ['Ethnicity', 'People'], 'washington-post': ['Media', 'News Outlet'],
     'doug-ducey': ['Politician', 'Republican'], 'washington-dc': ['City'], 'obamacare': ['Healthcare', 'Policy'],
     'adam-schiff': ['Politician', 'Democrat'], 'cooper-governor': ['Politician', 'Democrat'],
     'penn-jillette': ['Magician'], 'brian-williams': ['Journalist', 'Media'],
     'cnn': ['Media', 'News Outlet'], 'bob-corker': ['Politician', 'Republican'],
     'charles-lane': ['Journalist Personnel'], 'chain-migration': ['Immigration', 'Policy'],
     'molly-sims': ['Model'], 'carter-page-fisa': ['Legal', 'Surveillance'],
     'bowe-bergdahl-decision': ['Legal', 'Military'], 'cnn-trump-documentary': ['Media', 'Documentary'],
     'establishment': ['Social Issues', 'Political'], 'nasa': ['Organization', 'Science'],
     'isis': ['Terrorist Organization'], 'rick-perry': ['Politician'],
     'andrew-gillum': ['Politician', 'Democrat'], 'marie-yovanovitch': ['Diplomat'],
     'megyn-kelly': ['Journalist Personnel'], 'seal-prosecutors': ['Legal', 'Military'],
     'united-nations': ['Organization', 'International Relations'],
     'existing-border-wall': ['Politics', 'Border Security'], 'dnc-emails': ['Politics', 'Emails'],
     'charles-krauthammer': ['Commentator'], 'chris-stirewalt': ['Political Analyst'],
     'middle-east-relations': ['International Relations', 'Politics'], 'gillian-turner': ['Journalist Personnel'],
     'donny-deutsch': ['Media Personnel'], 'new-york-daily-news': ['Media', 'News Outlet'],
     'democratic-primaries': ['Politics', 'Elections'], 'wall-street-journal-editorial-board': ['Media', 'News Outlet'],
     'democrat-run-cities': ['Politics', 'Cities'], 'bob-iger': ['Business Personnel'],
     'barbara-res': ['Business Personnel'], 'tony-schwartz': ['Author'],
     'jeb-bush-supporters': ['Politician', 'Republican'], 'fox-polls': ['Media', 'Polls'],
     'jonathan-martin': ['Journalist Personnel'], 'jeff-bezos': ['Business Personnel'],
     'refugee-crisis-in-europe': ['International Relations', 'Crisis'], 'blm': ['Movement', 'Social Issues'],
     'us-census': ['Government', 'Data'], 'hillary-clinton': ['Politician'],
     'robert-mueller': ['Legal Personnel'], 'david-green': ['Business Personnel'],
     'our-visa-system': ['Government', 'Immigration'], 'msnbc': ['Media', 'News Outlet'],
     'stephen-sisolak': ['Politician', 'Governor'],
     'investigations-of-trump-presidency': ['Politics', 'Investigations'], 'eric-schneiderman': ['Legal Personnel'],
     'republican-party': ['Political Party'], 'lester-holt': ['Journalist', 'Media'], 'hollywood': ['Entertainment'],
     'ricardo-rossello': ['Politician', 'Governor'], 'bret-stephens': ['Journalist Personnel'],
     'bill-deblasio': ['Politician', 'Mayor'], 'terrorists': ['Security', 'Terrorism'],
     'google': ['Company', 'Technology'], 'stanley-mcchrystal': ['Military Personnel'], 'amy-mcgrath': ['Politician'],
     '60-minutes': ['Media', 'TV Show'], 'dick-durbin': ['Politician', 'Democrat'],
     'debra-messing': ['Actor'], 'pa-recount': ['Politics', 'Elections'], 'the-media': ['Media'],
     'tim-ryan': ['Politician', 'Democrat'], 'alicia-machado': ['Actor'], 'don-mcgahn': ['Legal Personnel'],
     'minneapolis': ['City'], 'supreme-court': ['Legal'], 'truth-lies-leadership': ['Book', 'Author'],
     'collin-peterson': ['Politician', 'Democrat'], 'graydon-carter': ['Journalist Personnel'],
     'a-b-stoddard': ['Journalist Personnel'], 'virtual-learning': ['Education', 'Technology'],
     'wsj-editorial-board': ['Media', 'Editorial Board'], 'lois-frankel': ['Politician', 'Democrat'],
     'uk-health-system': ['Healthcare', 'International'], 'jonathan-karl': ['Journalist', 'Media'],
     'trade-pacts': ['Trade', 'Politics'], 'merck-pharma': ['Company', 'Pharmaceuticals'],
     'steve-bullock': ['Politician', 'Democrat'], 'ted-cruz': ['Politician', 'Republican'],
     'european-union': ['International Relations'], 'new-jersey': ['State'], 'jake-tapper': ['Journalist', 'Media'],
     'bad-deals': ['Politics'], 'california-train-project': ['Infrastructure', 'Transportation'],
     'nfl': ['Sports', 'Football'], 'bakari-sellers': ['Political Commentator'],
     'aaron-zebley': ['Legal Personnel'], 'super-bowl-50': ['Sports', 'Football'],
     'us-trade-representatives': ['Government', 'Trade'], 'republicans': ['Political Party'],
     'cdc': ['Organization', 'Health'], 'manafort-sentence': ['Legal'], 'cbs': ['Media', 'TV Network'],
     'jon-ossoff': ['Politician', 'Democrat'], 'veronica-escobar': ['Politician', 'Democrat'],
     'cruz-kasich-pact': ['Politics'], 'new-day': ['Media', 'TV Show'], 'jeffrey-goldberg': ['Journalist Personnel'],
     'robert-gates': ['Military Personnel'], 'hunter-biden': ['Government Personnel'],
     'gonzalo-curiel': ['Legal Personnel'],
     'pollsters': ['Politics'], 'atlantic-article-about-cemetery-comments': ['Media', 'Article'],
     'us-court-system': ['Legal'], 'cheri-jacobus': ['Political Commentator'],
     'mark-halperin': ['Journalist Personnel'], 'tallahassee': ['City'], 'nbc-news': ['Media', 'News Outlet'],
     'illinois': ['State'], 'us-government': ['Government'],
     'past-presidential-administrations': ['Politics', 'History'], 'common-core': ['Education'],
     'kweisi-mfume': ['Politician', 'Democrat'], 'levar-ball': ['Sports Personnel'],
     'theresa-greenfield': ['Politician', 'Democrat'], 'hamilton-cast': ['Entertainment', 'Theater'],
     'michael-nutter': ['Politician', 'Democrat'], 'john-allen': ['Military Personnel'], 'china': ['Country'],
     'trump-critics': ['Politics'], 'ralph-northam': ['Politician', 'Governor'],
     'dan-henninger': ['Journalist Personnel'], 'obama-justice-department': ['Politics', 'Legal'],
     'legal-system': ['Legal'], 'fcc': ['Government', 'Regulation'], 'md-7': ['State'],
     'wsj-nbc-poll': ['Media', 'Polls'], 'pulitzer-prizes': ['Media', 'Awards'],
     'iowa-caucus-2020': ['Politics', 'Elections'], 'andrew-napolitano': ['Legal Personnel'],
     'gitmo-prisoner-release': ['Legal', 'Military'], 'laurene-powell-jobs': ['Business Personnel'],
     'lisa-murkowski': ['Politician', 'Republican'], 'democratic-disaster-bill': ['Politics', 'Legislation'],
     'tavis-smiley': ['Media Personnel'], 'refugees-in-germany': ['International Relations', 'Refugees'],
     'congress': ['Government'], 'christopher-steele': ['Politics Personnel'], 'biden-administration': ['Politics'],
     'melinda-henneberger': ['Journalist Personnel'], 'immigration-lottery-system': ['Immigration'],
     'hallie-jackson': ['Journalist', 'Media'], 'jeb-bush-campaign': ['Politician', 'Republican'],
     'john-legere': ['Business Personnel'], 'virginia-economy': ['Economy', 'State'],
     'north-korea-experts': ['International Relations', 'Experts'], 'comcast': ['Company', 'Media'],
     'howard-schultz': ['Business Personnel'], 'carl-d-leonnig': ['Journalist Personnel'],
     'aoc': ['Politician', 'Democrat'], 'justin-trudeau': ['Politician', 'Prime Minister'],
     'stephen-colbert': ['Entertainment Personnel'],
     'us-australia-refugee-deal': ['International Relations', 'Refugees'], 'maureen-dowd': ['Journalist Personnel'],
     'steve-scully': ['Journalist Personnel'], 'anderson-cooper': ['Journalist Personnel'],
     'beto-orourke': ['Politician', 'Democrat'], 'erick-erickson': ['Conservative Personnel'],
     'ted-cruz-iowa-speech': ['Politician', 'Republican'], 'john-kasichs-ad-guy': ['Political Strategist'],
     'goodyear-tires': ['Company', 'Automotive'], 'frank-luntz': ['Political Consultant'],
     'lovely-warren': ['Politician', 'Mayor'], 'meghan-mccain': ['Media Personnel'],
     'russell-moore': ['Religious Leader'], 'whistleblower-complaint': ['Legal', 'Whistleblower'],
     'mika-brzezinski': ['Journalist Personnel'], 'detroit': ['City'], 'special-interests': ['Politics'],
     'section-230': ['Legal', 'Technology'], 'george-pataki': ['Politician', 'Republican'], 'debates': ['Politics'],
     'ucla-basketball-players': ['Sports', 'Basketball'], 'chris-coons': ['Politician', 'Democrat'],
     'nancy-pelosi': ['Politician', 'Democrat'], 'david-gregory': ['Journalist Personnel'],
     'mark-warner': ['Politician', 'Democrat'], 'jacob-frey': ['Politician', 'Mayor'],
     'dnc-chairmanship-election': ['Politics', 'Elections'], 'buzzfeed': ['Media', 'News Outlet'],
     'tom-steyer': ['Business Personnel'], 'anderson-cooper-360': ['Journalist Personnel'],
     'nellie-ohr': ['Legal Personnel'], 'john-mccain': ['Politician'],
     'big-game-hunting': ['Sports', 'Hunting'], 'lawrence-o-donnell': ['Journalist Personnel'],
     'jerome-powell': ['Economics Personnel'], 'jussie-smollet': ['Entertainment Personnel'],
     'benghazi-hearings': ['Politics', 'Investigations'], 'delegate-system': ['Politics', 'Elections'],
     'john-podesta': ['Politician'], 'us-intelligence-agencies': ['Government', 'Intelligence'],
     'debate-microphone': ['Politics', 'Debates'], 'oreilly-factor': ['Media', 'TV Show'],
     'sadiq-khan': ['Politician', 'Mayor'], 'kyrsten-sinema': ['Politician', 'Democrat'],
     'obama-administration': ['Politician', 'Government'], 'yoel-roth': ['Social Media Personnel'],
     'espn': ['Media', 'Sports'], 'charles-blow': ['Journalist Personnel'], 'elizabeth-beck': ['Legal Personnel'],
     'full-frontal': ['Media', 'TV Show'], 'bill-maher': ['Entertainment Personnel'], 'trade-deals': ['Politics'],
     'ben-sasse': ['Politician', 'Republican'], 'spygate': ['Politics'], 'lisa-page': ['Legal Personnel'],
     'john-kerry': ['Politician', 'Democrat'], 'thomas-massie': ['Politician', 'Republican'],
     'maxine-waters': ['Politician', 'Democrat'], 'voters': ['Politics'], 'bette-midler': ['Entertainment Personnel'],
     'paul-singer': ['Business Personnel'], 'world-trade-organization': ['International Relations', 'Economics'],
     'impeachment-inquiry': ['Politics'], 'matthew-dowd': ['Journalist Personnel'], 'stone-judge': ['Legal Personnel'],
     'harley-davidson': ['Company', 'Automotive'], 'mitt-romney': ['Politician', 'Republican'],
     'max-rose': ['Politician', 'Democrat'], 'katie-couric': ['Journalist Personnel'],
     'state-of-the-union': ['Politics', 'Speech'], 'bernard-goldberg': ['Journalist Personnel'],
     'arrested-saudis': ['International Relations', 'Legal'], 'alec-baldwin': ['Entertainment Personnel'],
     'new-air-force-one': ['Government', 'Aviation'], 'john-hickenlooper': ['Politician', 'Democrat'],
     'jb-pritzger': ['Politician', 'Governor'], 'richard-blumenthal': ['Politician', 'Democrat'],
     'loretta-lynch': ['Legal Personnel'], 'polling-establishment': ['Politics', 'Polls'],
     'ana-navarro': ['Political Commentator'], 'milwaukee': ['City'],
     'sherrod-brown': ['Politician', 'Democrat'], 'mark-cuban': ['Business Personnel'],
     'fbi': ['Government', 'Law Enforcement'], 'puerto-rico': ['Territory'], 'dana-nessel': ['Legal Personnel'],
     'abc-post-poll': ['Media', 'Polls'], 'anthony-fauci': ['Health Personnel'],
     'angela-merkel': ['Politician', 'Chancellor'],
     'states-refusing-to-give-voter-panel-info': ['Politics', 'Elections'],
     'jeb-staffer': ['Political Staff'], 'chris-wallace': ['Journalist Personnel'],
     'jay-inslee': ['Politician', 'Governor'], 'russia-bounty-story': ['International Relations', 'News'],
     'chris-krebs': ['Security Personnel'], 'the-room-where-it-happened': ['Book'],
     'colin-kaepernick': ['Sport Personnel'], 'fusion-gps': ['Company', 'Political Research'],
     'pakistan': ['Country'], 'george-papadopolous': ['Political Figure'],
     'jocelyn-benson': ['Politician'], 'des-moines-register': ['Media', 'Newspaper'],
     'joe-donnely': ['Politician', 'Democrat'], 'jennifer-rubin': ['Journalist Personnel'],
     'hugh-hewitt': ['Media Personnel'], 'rockin-in-the-free-world': ['Music'], 'nascar': ['Sports', 'Auto Racing'],
     'nbc-executives': ['Company', 'Media'], 'chris-cuomo': ['Journalist Personnel'],
     'inside-politics': ['Media', 'TV Show'], 'new-york': ['City'], 'the-new-yorker': ['Media', 'Magazine'],
     'california-cars': ['Automotive', 'State'], 'john-dean': ['Legal Personnel'],
     'gavin-newsom': ['Politician', 'Governor'], 'jerry-brown': ['Politician', 'Governor'], 'rinos-tk': ['Politics'],
     'arianna-huffington': ['Media Personnel'], 'rick-scott': ['Politician', 'Republican'],
     'us-immigration-policies': ['Politics', 'Immigration'], 'sweden': ['Country'],
     'brian-stelter': ['Journalist Personnel'], 'rage-book': ['Book'], 'bandon-dunes': ['Sports', 'Golf'],
     'united-kingdom': ['Country'], 'twitter': ['Social Media'],
     'political-ads-in-indiana': ['Politics', 'Advertisements'], 'arnold-schwarzenegger': ['Actor'],
     'epi-pens': ['Health', 'Medicine'], 'william-weld': ['Politician'],
     'nato': ['International Relations', 'Organization'], 'jobs-report': ['Economy', 'Report'],
     'cory-booker': ['Politician', 'Democrat'], 'barbara-underwood': ['Legal Personnel'],
     'dean-baquet': ['Journalist Personnel'], 'minneapolis-looters': ['City', 'Crime'],
     'joy-behar': ['Entertainment Personnel'], 'ninth-circuit': ['Legal', 'Court'],
     'kirsten-gillibrand': ['Politician', 'Democrat'], 'trump-opposition': ['Politics'],
     'the-new-york-times': ['Media', 'Newspaper'], 'union-leader': ['Media', 'Newspaper'],
     'saturday-night-live': ['Media', 'TV Show'], 'vladimir-putin': ['Politician'],
     'jon-tester': ['Politician', 'Democrat'], 'marc-elias': ['Legal Personnel'], 'roger-goodell': ['Sports Personnel'],
     'supreme-court-protestors': ['Legal', 'Protest'], 'koch-brothers': ['Business Personnel'],
     'john-roberts': ['Judgen'], 'jimmy-kimmel': ['Entertainment Personnel'],
     'mort-zuckerman': ['Business Personnel'], 'tim-kaine': ['Politician', 'Democrat'],
     'fbi-investigation-of-hillary': ['Politics', 'Investigations'], 'george-will': ['Journalist Personnel'],
     'fortune-magazine': ['Media', 'Magazine'], 'stacey-abrams': ['Politician', 'Democrat'],
     'dem-convention-2020': ['Politics', 'Event'], 'steve-kerr': ['Sports Personnel'],
     'lesley-stahl': ['Journalist Personnel'], 'john-brennan': ['Government Personnel'],
     'former-us-presidents': ['Politicians'], 'michael-deantonio': ['Author'], 'united-states': ['Country'],
     'shephard-smith': ['Journalist Personnel'], 'richard-trumka': ['Union Leader'],
     'drudge-report': ['Media', 'Website'], 'anna-wintour': ['Fashion Personnel'],
     'brad-raffensperger': ['Politician'], 'politically-correct-fools': ['Politics'],
     'us-leaders': ['Politicians'], 'brian-kilmeade': ['Media Personnel'], 'vandals-in-nc': ['Crime'],
     'repub-presidential-primary-challengers-2020': ['Politics'], 'bobby-jindal': ['Politician', 'Republican'],
     'biden-staff': ['Politics'], 'never-trumpers': ['Politics'], 'chuck-schumer': ['Politician', 'Democrat'],
     'chrissy-teigen': ['Entertainment Personnel'], 'nicole-wallace': ['Political Commentator'],
     'prince-alwaleed-bin-talal': ['Business Personnel'], 'email-investigation': ['Politics'],
     'rachel-maddow': ['Journalist Personnel'], 'willie-geist': ['Journalist Personnel'], 'obamagate': ['Politics'],
     'other-republican-candidates': ['Politics'], 'john-roberts-fox': ['Journalist Personnel'],
     'stefan-lofven': ['Politician', 'Prime Minister'], 'doug-jones': ['Politician', 'Democrat'],
     'republican-candidates': ['Politics'], 'the-republican-establishment': ['Politics'],
     'virginia-republican-party': ['Political Party', 'State'], 'steve-bannon': ['Political Strategist'],
     'joe-crowley': ['Politician'], 'cnn-international': ['Media', 'TV Network'],
     'chelsea-manning': ['Whistleblower'], 'bill-nelson': ['Politician'],
     'auto-executives': ['Business', 'Automotive'], 'pfizer': ['Company', 'Pharmaceutical'],
     'chris-hahn': ['Political Commentator'], 'team-of-vipers': ['Book'],
     'marc-thiessen': ['Columnist'], 'juan-williams': ['Journalist Personnel'],
     'democratic-national-committee': ['Political Organization'], 'late-night-television': ['Media', 'TV Show'],
     'paris-agreement': ['International Relations', 'Climate'], 'debt-ceiling-approval': ['Politics', 'Economy'],
     'house-democrats': ['Politicians', 'Democratic Party'], 'andy-lack': ['Media Executive Personnel'],
     'hamilton': ['Entertainment', 'Musical'], 'rick-wilson': ['Political Strategist'],
     'karl-roves-book': ['Book'], 'late-night-television-hosts': ['Media', 'TV Show'],
     'ilhan-omar': ['Politician'], 'haywood-s-gilliam': ['Judgen'],
     'sam-nunberg': ['Political Consultant'], 'charles-koch': ['Business Personnel'],
     'womens-assault-allegations': ['Social Issues', 'Gender'], 'cnn-panelists': ['Media', 'TV Show'],
     'fbi-investigation-of-hillarys-emails': ['Politics', 'Investigations'],
     'very-stable-genius': ["Trump's Phrase"], 'flag-burners': ['Social Issues', 'Protest'],
     'ga-2020-recount': ['Politics', 'Elections'], 'john-thune': ['Politician'],
     'iran-deal': ['International Relations'], 'alisyn-camerota': ['Journalist Personnel'], 'brussels': ['City'],
     'bloomberg-news': ['Media', 'News'], 'democratic-house-committee': ['Politics', 'Committee'],
     'california': ['State'], 'carl-bernstein': ['Journalist Personnel'], 'larry-hogan': ['Politician', 'Governor'],
     'new-york-sea-wall': ['Infrastructure', 'New York'], 'russia': ['Country'],
     'samuel-l-jackson': ['Actor'], 'tsa': ['Government Agency', 'Security'], 'chicago': ['City'],
     'trump-report': ['Politics'], 'rodrigo-duterte': ['Politician'], 'david-kris': ['Legal Personnel'],
     'germany': ['Country'], 'biden-ad': ['Politics', 'Advertisements'], 'quinnipiac-polls': ['Polls'],
     'michael-bloomberg': ['Business Personnel'], 'recounts-in-florida': ['Politics', 'Elections'],
     'rich-lowry': ['Journalist Personnel'], 'nafta': ['International Relations', 'Trade'],
     'joe-scarborough': ['TV Host'], 'pundits': ['Media', 'Commentators'],
     'brenda-snipes': ['Election Official Personnel'], 'maggie-haberman': ['Journalist Personnel'],
     'politicians': ['Politicians'], 'erin-burnett': ['Journalist Personnel'],
     'emmanuel-macron': ['Politician'], 'polls': ['Polls'], 'spike-lee': ['Director'],
     'ruth-marcus-book': ['Book'], 'peter-baker': ['Journalist Personnel'],
     'whoopi-goldberg': ['Entertainer'], 'wreath-cancellation-policy': ['Policy'],
     'jeff-sessions': ['Politician'], 'jared-polis': ['Politician', 'Governor'],
     'protesters': ['Social Issues', 'Protest'], 'ig-report': ['Politics', 'Investigations'],
     'david-cicilline': ['Politician'], 'the-clintons': ['Political Family'],
     'peter-strzok': ['FBI Agent'], 'democrats-nunes-memo': ['Politics', 'Memo'],
     'stormy-daniels-alleged-assailant': ['Legal Personnel'], 'harry-hurt': ['Journalist Personnel'],
     'mueller-report': ['Politics', 'Investigations'], 'lincoln-chafee': ['Politician'],
     'joe-biden': ['Politician'], 'baltimore': ['City'], 'lebron-james': ['Athlete'],
     'omarosa-manigault': ['TV Personality Personnel'], 'kneeling-nfl-players': ['Sports', 'Protest'],
     'mueller-team': ['Politics', 'Investigations'], 'robert-deniro': ['Actor'],
     'paul-krugman': ['Economist'], 'dana-perino': ['TV Host Personnel'], 'meryl-streep': ['Actor'],
     'muriel-bowser': ['Politician'], 'kate-brown': ['Governor'],
     'rashida-tlaib': ['Politician'], 'ted-wheeler': ['Politician'],
     'kathy-griffin': ['Comedian'], 'nsa': ['Government Agency'], 'elites': ['Social Issues'],
     'hunter-bidens-laptop': ['Politics', 'Scandal'], 'claire-mccaskill': ['Politician'],
     'canada': ['Country'], 'fda': ['Government Agency', 'Health'], 'losers-haters': ['Social Issues', 'Criticism'],
     'caravans': ['Social Issues', 'Immigration'], 'michelle-wolf': ['Comedian'],
     'ken-frazier': ['Business Personnel'], 'rexnord': ['Company', 'Manufacturing'],
     'rick-snyder': ['Politician'], 'bob-woodward': ['Journalist Personnel'],
     'jamie-dimon': ['Business Personnel'], 'commission-on-presidential-debates': ['Organization', 'Debates'],
     'pharma-ad': ['Advertising', 'Pharmaceutical'], 'al-sharpton': ['Activist'],
     'frank-vandersloot': ['Business Personnel'], 'brett-mcgurk': ['Government Personnel'],
     'rex-tillerson': ['Government Personnel'], 'manufacturing-ceos': ['Business', 'Manufacturing'],
     'catch-and-release': ['Social Issues', 'Immigration'], 'iowa-democratic-party': ['Political Party', 'State'],
     'evan-mcmullin': ['Politician'], '2016-election': ['Politics', 'Elections'],
     'paulina-vega': ['Beauty Queen Personnel'], 'paul-begala': ['Political Consultant'],
     'forbes': ['Media', 'Magazine'], 'scott-walker': ['Politician'], 'vanity-fair': ['Media', 'Magazine'],
     'dianne-feinstein': ['Politician'], 'pete-ricketts': ['Governor'],
     'snoop-dogg': ['Musician'], 'frank-bruni': ['Journalist Personnel'],
     'george-h-w-bush': ['Former President'], 'mary-trump': ['Family Member'],
     'woody-johnson': ['Business Personnel'], 'gretchen-whitmer': ['Governor'], 'palestine': ['Country'],
     'el-salvador': ['Country'], 'the-oscars': ['Entertainment', 'Awards'], 'comcast-executives': ['Company', 'Media'],
     'al-franken': ['Politician'], 'michael-avenatti': ['Lawyer'],
     'joe-manchin': ['Politician'], 'amy-klobuchar': ['Politician'],
     'us-legal-system': ['Legal', 'System'], 'mike-pence': ['Vice President Personnel'],
     'super-pacs': ['Politics', 'Campaign Finance'], 'gm-plant-ohio': ['Business', 'Manufacturing'],
     'bob-vander-plaats': ['Activist'], 'mccabe-memos': ['Government Personnel'],
     'chemical-attack-syria': ['Politics', 'International Relations'], 'amy-chozick': ['Journalist Personnel'],
     'honduras': ['Country'], 'vote-count-michigan': ['Politics', 'Elections'], 'george-conway': ['Lawyer'],
     'french-wine': ['Food and Drink', 'Wine'], 'theresa-may': ['Politician'],
     'eddie-johnson': ['Police Personnel'], 'jeff-horwitz': ['Journalist Personnel'],
     'carly-fiorina': ['Business Personnel'], 'boston-globe': ['Media', 'Newspaper'], 'macys': ['Company', 'Retail'],
     'the-view': ['Media', 'TV Show'], 'seattle-portland-protesters': ['Social Issues', 'Protests'],
     'ruth-marcus': ['Journalist Personnel'], 'national-review': ['Media', 'Magazine'],
     'the-courts': ['Legal', 'Courts'], 'anthony-scaramucci': ['Business Personnel'],
     'mitch-mcconnell': ['Politician'], 'neil-young': ['Musician'],
     'john-harwood': ['Journalist Personnel'], 'roger-stone-sentence': ['Legal Personnel'],
     'letitia-james': ['Attorney General'], 'karen-bass': ['Politician'],
     'lindsey-graham': ['Politician'], 'richard-cordray': ['Government Personnel'],
     'new-york-democrats': ['Political Party', 'State'], 'coronavirus': ['Health', 'Pandemic'],
     'tpp-deal': ['Politics', 'Trade'], 'florida-early-voting': ['Politics', 'Elections'],
     'the-establishment': ['Politics', 'System'], 'gustavo-petro': ['Politician'],
     'democratic-national-convention': ['Political Party', 'Event'], 'jeb-bush': ['Politician'],
     'rnc': ['Political Party', 'Event'], 'trump-russia': ['Politics', 'Investigations'],
     'susan-rice': ['Politician'], 'ali-khamenei': ['Religious Leader'],
     'julian-castro': ['Politician'], 'pennsylvania': ['State'], 'brian-ross': ['Journalist Personnel'],
     'james-robart': ['Judgen'], 'greta-thunberg': ['Activist'],
     'small-wall-section': ['Politics', 'Immigration'], 'richard-goodstein': ['Political Consultant'],
     'debbie-wasserman-schultz': ['Politician'], 'kamala-harris': ['Politician'],
     'comey-memos': ['Government Personnel'], 'water-lanes': ['Politics', 'Infrastructure'],
     'mueller-hearings': ['Politics', 'Investigations'], 'wisconsin-recount': ['Politics', 'Elections'],
     'seth-meyers': ['Comedian'], 'la-dodgers-relievers': ['Sports', 'Baseball'],
     'drug-cartels': ['Crime', 'Drug Trade'], 'jennifer-griffin': ['Journalist Personnel'],
     '2020-dem-candidates': ['Politics', 'Elections'], 'philadelphia': ['City'],
     'supporters-of-middle-east-wars': ['Politics', 'War'], 'first-100-days': ['Politics', 'Government'],
     'joe-walsh': ['Politician'], 'brit-hume': ['Journalist Personnel'],
     'club-for-growth': ['Organization', 'Economic Policy'], 'democratic-debate-july-30': ['Politics', 'Debates'],
     'tom-ridge': ['Politician'], 'political-ads': ['Politics', 'Advertising'],
     'michael-moore-show': ['Media', 'TV Show'], 'presidential-candidates': ['Politics', 'Elections'],
     'ronda-rousey': ['Athlete'], 'anthony-weiner': ['Politician'],
     'kate-steinle-verdict': ['Legal', 'Verdict'], 'anne-karni': ['Journalist Personnel'],
     'andrew-mccabe': ['Government Personnel'], 'the-squad': ['Politics', 'Group'],
     'single-payer-health-plan': ['Politics', 'Healthcare'], 'thomas-frieden': ['Government Personnel'],
     'amazon': ['Company', 'Retail'], 'intelligence-leakers': ['Politics', 'Security'],
     'scotus-rally': ['Politics', 'Protests'], 'town-hall-meetings': ['Politics', 'Events'],
     'weekly-standard': ['Media', 'Magazine'], 'jeff-flake': ['Politician'],
     'eric-swalwell': ['Politician'], 'calif-12': ['Politics', 'District'],
     'alexander-vindman': ['Government Personnel'], 'states-with-dem-governors': ['Politics', 'Governors'],
     'peggy-noonan': ['Journalist Personnel'], 'red-state': ['Politics', 'State'],
     'anti-trump-ads': ['Politics', 'Advertising'], 'bruce-ohr': ['Government Personnel'],
     'usps': ['Organization', 'Postal Service'], 'trumps-taxes': ['Politics', 'Taxation'],
     'undocumented-immigrants': ['Politics', 'Immigration'], 'fox-news-sunday': ['Media', 'TV Show'],
     'harry-reid': ['Politician'], 'james-comey': ['Government Personnel'],
     'john-kasich': ['Politician'], 'james-clyburn': ['Politician'],
     'oval-office-podium': ['Politics', 'Government'], 'london': ['City'], 's-e-cupp': ['Journalist Personnel'],
     'donna-brazile': ['Political Strategist'], 'state-department': ['Organization', 'Government'],
     'democratic-debate': ['Politics', 'Debates'], 'pledge-of-allegiance-decision-slp': ['Legal', 'Decision'],
     'jamie-weinstein': ['Journalist Personnel'], 'leakers': ['Politics', 'Security'],
     'ted-cruz-campaign': ['Politics', 'Campaign'], 'megan-rapinoe': ['Athlete'],
     'politico': ['Media', 'Website'], 'fox-news-debate': ['Media', 'TV Show'],
     'filibuster-rule': ['Politics', 'Government'], 'nevada': ['State'], 'ben-carson': ['Politician'],
     'whca-dinner': ['Politics', 'Event'], 'tom-llamas': ['Journalist Personnel'],
     'elijah-cummings': ['Politician'], 'justin-amash': ['Politician'],
     'the-system': ['Politics', 'Government'], 'wall-of-moms': ['Social Issues', 'Protests'],
     'univision': ['Media', 'TV Network'], 'michael-wolff': ['Author'],
     'mark-sanford': ['Politician'], 'democrat-run-states': ['Politics', 'State'],
     'chuck-todd': ['Journalist Personnel'], 'john-lewis': ['Politician'],
     'joy-ann-reid': ['Journalist Personnel'], 'nbc': ['Media', 'TV Network'], 'ca-28': ['Politics', 'District'],
     'endless-wars': ['Politics', 'War'], '2020-pres-debate??': ['Politics', 'Debates'],
     'dc-leaders?': ['Politics', 'Government'], 'dc-police': ['Organization', 'Law Enforcement'],
     'blm-protesters': ['Social Issues', 'Protests'], 'iran': ['Country'], 'geoff-duncan': ['Politician'],
     'draghi-stimulus-remarks': ['Economics', 'Remarks'], 'ronald-klain': ['Government Personnel'],
     'anthony-brindisi': ['Politician'], 'brandon-victor-dixon': ['Actor'],
     'cnn-polls': ['Media', 'Polling'], 'clare-o-connor': ['Journalist Personnel'],
     'donna-shalala': ['Politician'], 'matt-bai': ['Journalist Personnel'], 'atlanta': ['City'],
     'juaquin-castro': ['Politician'], 'ben-schreckenger': ['Journalist Personnel'],
     'today-show': ['Media', 'TV Show'], 'bill-kristol': ['Political Commentator'],
     'norah-o-donnell': ['Journalist Personnel'], 'bob-casey': ['Politician'],
     'decision-to-disqualify-horse': ['Sports', 'Horse Racing'], 'errol-louis': ['Journalist Personnel'],
     'glenn-beck': ['Media Personality'], 'jemele-hill': ['Journalist Personnel'], 'portland': ['City'],
     'nonsupporting-republicans': ['Politics', 'Republicans'], 'uk-ambassador': ['Politics', 'Diplomacy'],
     '2020-election': ['Politics', 'Elections'], 'debbie-stabenow': ['Politician'],
     'afl-cio': ['Organization', 'Labor Union'], 'daca-kids': ['Politics', 'Immigration'],
     'huma-abedin': ['Political Figure'], 'joe-mcquaid': ['Journalist Personnel'],
     'washington-insiders': ['Politics', 'Insiders'], 'sally-yates': ['Government Personnel'],
     'united-steelworkers': ['Organization', 'Labor Union'], 'pramila-jayapal': ['Politician'],
     'morning-joe': ['Media', 'TV Show'], 'john-king': ['Journalist Personnel'],
     'tammy-baldwin': ['Politician'], 'cliff-sims': ['Author'],
     'general-motors': ['Company', 'Automotive'], 'nate-silver': ['Statistician'], 'south-bend': ['City'],
     'the-red-hen': ['Business', 'Restaurant'], 'senate-republicans': ['Politics', 'Republicans'],
     'firefighters-union': ['Organization', 'Labor Union'], 'katie-rogers': ['Journalist Personnel'],
     'usa-today': ['Media', 'Newspaper'], 'mary-katharine-ham': ['Journalist Personnel'],
     'mark-herring': ['Politician'], 'dnc': ['Organization', 'Political Party'],
     'alleged-nyc-terrorist': ['Crime', 'Terrorism'], 'john-oliver': ['Comedian'],
     'ny-prosecutors': ['Organization', 'Legal'], 'big-tech': ['Business', 'Technology'],
     'california-water-use': ['Politics', 'Environment'], 'major-garrett': ['Journalist Personnel'],
     'rick-bright': ['Government Personnel'], 'nikki-haley': ['Politician'],
     'michael-morell': ['Government Personnel'], 'stephen-hahn': ['Government Personnel'],
     'jerry-nadler': ['Politician'], 'mail-in-voting': ['Politics', 'Voting'],
     'carl-cameron': ['Journalist Personnel'], 'carmen-yulin-cruz': ['Politician'],
     'steve-schmidt': ['Political Strategist'], 'kristen-welker': ['Journalist Personnel'],
     'democratic-candidates': ['Politics', 'Elections'], 'puerto-rico-infrastructure': ['Politics', 'Infrastructure'],
     'emmys-2017': ['Media', 'Awards'], 'deb-sopan': ['Journalist Personnel'], 'facebook': ['Company', 'Social Media'],
     'philip-rucker': ['Journalist Personnel'], 'department-of-justice': ['Organization', 'Legal'],
     'stephanie-rawlings-blake': ['Politician'], 'bill-clinton': ['Former President'],
     'conor-lamb': ['Politician'], 'ca-25-election': ['Politics', 'Elections'],
     'strzok-page-texts': ['Politics', 'Texts'], 'schiff-memo': ['Politics', 'Memo'],
     'bias-free-language-guide': ['Politics', 'Language'], 'elizabeth-warren': ['Politician'],
     'senate-democrats': ['Politics', 'Democrats'], 'ben-cardin': ['Politician'],
     'lisa-belkin': ['Journalist Personnel'], 'chuck-jones': ['Labor Leader'],
     'james-clapper': ['Government Personnel'], 'sanctuary-cities': ['Politics', 'Cities'],
     'nordstrom': ['Business', 'Retail'], 'california-environmental-laws': ['Politics', 'Environment'],
     'san-francisco': ['City'], 'green-new-deal': ['Politics', 'Environment'],
     'judge-appointments-delay-tactics': ['Politics', 'Judiciary'], 'sarah-jeong': ['Journalist Personnel'],
     'joe-cunningham': ['Politician'], 'larry-sabato': ['Political Analyst'],
     'paul-ryan': ['Politician'], 'people': ['General Term'], 'marshawn-lynch': ['Athlete'],
     'opec': ['Organization', 'Oil'], 'jenny-durkan': ['Politician'],
     'internal-revenue-service': ['Organization', 'Government'], 'jim-mattis': ['Government Personnel'],
     'kim-jong-un': ['Politician'], 'bashar-al-assad': ['Politician'], 'north-korea': ['Country'],
     'southern-border': ['Politics', 'Borders'], 'world-news-tonight': ['Media', 'TV Show'],
     'stuart-stevens': ['Political Consultant'], 'debbie-dingell': ['Politician'],
     'david-cay-johnston': ['Journalist Personnel'], 'face-the-nation': ['Media', 'TV Show'],
     'harley-rouda': ['Politician'], 'dave-weigel': ['Journalist Personnel'],
     'nc-ballot-extension': ['Politics', 'Elections'], 'civil-war-memorial-opponents': ['Politics', 'Memorials'],
     'the-fed': ['Organization', 'Economics'], 'headline': ['Media', 'News'], 'illegal-leaks': ['Politics', 'Leaks'],
     'antifa': ['Organization', 'Protest Movement'], 'illegal-immigration': ['Politics', 'Immigration'],
     'kasie-hunt': ['Journalist Personnel'], 'travel-ban': ['Politics', 'Immigration'],
     'abc-news': ['Media', 'News Network'], 'ashley-parker': ['Journalist Personnel'],
     'mikie-sherrill': ['Politician'], 'jeff-zucker': ['Media Executive Personnel'],
     'michael-cohen': ['Lawyer'], 'jimmy-fallon': ['Comedian'],
     'biden-family': ['Biden Family'], 'stone-juror': ['Juror'],
     'the-individual-mandate': ['Politics', 'Healthcare'], 'mayor-pete': ['Politician'],
     'decision-to-halt-the-ban': ['Politics', 'Immigration'], 'clinton-foundation': ['Organization', 'Charity'],
     'cnbc': ['Media', 'News Network'], 'don-lemon': ['Journalist Personnel'],
     'justin-fairfax': ['Politician'], 'nytimes-article': ['Media', 'Newspaper'],
     'john-bel-edwards': ['Politician'], 'books-critical-of-president-trump': ['Media', 'Books'],
     'bitcoin': ['Business', 'Cryptocurrency'], 'us-korea-military-exercises': ['Politics', 'Military'],
     'abc-politics': ['Media', 'Politics'], 'john-sununu': ['Politician'],
     'associated-press': ['Media', 'News Agency'], 'guatemala': ['Country'],
     'puerto-rico-aid-relief': ['Politics', 'Aid'], 'pat-toomey': ['Politician'],
     'ann-coulter': ['Commentator'], 'david-brooks': ['Journalist Personnel'],
     'dave-roberts': ['Athlete'], 'charlie-baker': ['Politician'],
     'sam-liccardo': ['Politician'], 'ga-2020-vote': ['Politics', 'Elections'],
     'ruth-bader-ginsburg': ['Judge'], 'frederica-wilson': ['Politician'],
     'serge-kovaleski': ['Journalist Personnel'], 'jeff-zeleny': ['Journalist Personnel'],
     'the-last-word-with-lawrence-o-donnell': ['Media', 'TV Show'], 'jill-colvin': ['Journalist Personnel'],
     'laws-about-sanctuary-cities': ['Politics', 'Cities'], 'fire-and-fury': ['Media', 'Book'],
     'andrew-cuomo': ['Politician'], 'christianity-today': ['Media', 'Magazine'],
     'dominion-voting': ['Business', 'Voting Systems'], 'cokie-roberts': ['Journalist Personnel'],
     'cfpb': ['Organization', 'Government'], 'lincoln-project': ['Organization', 'Political Action Committee'],
     'freedom-caucus': ['Organization', 'Political Group'], 'wall-street-journal': ['Media', 'Newspaper'],
     'michael-barbaro': ['Journalist Personnel'], 'brian-kemp': ['Politician'],
     'nba': ['Organization', 'Sports League'], 'new-york-city': ['City'],
     'veterans-affairs': ['Organization', 'Government'], 'meet-the-press': ['Media', 'TV Show'],
     'the-atlantic': ['Media', 'Magazine'], 'barack-obama': ['Politician'],
     'michael-flynn-case': ['Legal Case'], 'matt-drudge': ['Journalist Personnel'],
     'fox-news': ['Media', 'News Network'], 'john-bolton': ['Politician'],
     'bernie-sanders': ['Politician'], 'marty-walsh': ['Politician'],
     'f35-program': ['Military', 'Aircraft'], 'huffington-post': ['Media', 'News Website']}
